### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11023]
Pre-release (early)

- [X] Runtime updates (https://github.com/neovim/neovim/pull/14424)
- [X] Bump deps in `third-party/CMakeLists.txt` 
  - [X] libuv (#11803)
  - [X] luajit (https://github.com/neovim/neovim/pull/14096)
  - [X] luv (https://github.com/neovim/neovim/pull/11092)
  - [X] luarocks (https://github.com/neovim/neovim/pull/10292)
  - [X] treesitter (3c2bc05)
- [X] Bump [luarocks packages](https://github.com/neovim/neovim/pull/8069/files)
  - [X] lua-client (https://github.com/neovim/neovim/pull/11837)
- [X] Bump neovim-qt in `third-party/CMakeLists.txt` (https://github.com/neovim/neovim/pull/13004, https://github.com/neovim/neovim/pull/14514)

Pre-release

- [X] Run `scripts/gen_api_vimdoc.py` (https://github.com/neovim/neovim/pull/13260)

Post-release

- [ ] Review [revisit-at-release issues](https://github.com/neovim/neovim/labels/revisit-at-release)
- [x] Update [releases](https://github.com/neovim/neovim/releases)
- [x] Document [breaking changes](https://github.com/neovim/neovim/wiki/Following-HEAD), if any
- [ ] Newsletter (https://github.com/neovim/neovim.github.io/pull/200, https://github.com/neovim/neovim/wiki/newsletter-%2311-:-the-0.5-release)

**Comment by ccope** [comment]
Looks like a stable package still hasn't  been uploaded to the Ubuntu PPA: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

Is that something that should be added to the release checklist?

**Comment by justinmk** [comment]
No,  we don't control that .

**Comment by ccope** [comment]
Oh interesting, it looked official so I never noticed that.

**Comment by h-michael** [comment]
This is a package a maintainer list.
https://launchpad.net/~neovim-ppa/+members#active

CC: @jamessan

**Comment by jamessan** [comment]
> Looks like a stable package still hasn't been uploaded to the Ubuntu PPA

The stable PPA is updated after I'm able to update the Debian package.  That hasn't happened yet because dependencies need to be packaged/updated.
