### ISSUE TITLE
LSP enhancements and  tracking issue

### ISSUE THREAD

**Issue by h-michael** [neovim/neovim#11389]
followup of #11336 

The built-in LSP client was merged.
I think there will be similar bug reports and questions for a while, so I will make an issue for that.

**Comment by XVilka** [comment]
What I think it better is probably to reuse the [GitHub Projects feature](https://help.github.com/en/articles/about-project-boards):
![](https://help.github.com/assets/images/help/projects/add-card-from-sidebar.gif)

**Comment by norcalli** [comment]
- callbacks and proper calculation of character offsets from the byte offsets is probably a big one. We decided that it would be good to modify the parameters received before they are passed to any user or builtin callbacks.
- Deciding on the final vimL interface is another one. I'm personally still on the fence about the `add_filetype_config` and `lsp#add_filetype_config` functions. I'd like to remove them and go back to the bare interface before stabilizing those.
- I also think that the `config.on_attach` likely needs to be changed to execute inside of the buffer its executing in instead of passing `bufnr` as a second parameter.

Then finally there is the matter of what the builtin callback design should look like. I'm of the mind to provide a lot of utilities in `vim.lsp.util` and then some basic defaults which mostly act as code samples for users to use.

However, the basic assumption I'm taking is that users will learn Lua. I don't really know how to design vimL interfaces, but I'm very good at Lua interfaces. If we want to keep a vimL interface, I think I will need help on that part.

Otherwise, I'm prototyping some other things inside of https://github.com/norcalli/nvim-common-lsp.

**Comment by norcalli** [comment]
@XVilka someone with write access would have to do that, but I agree. For this, it's probably a good idea to use that.

**Comment by bfredl** [comment]
Some TODO items from the PR:

- [ ] For servers that only support full sync: we should throttle full buffer updates in some situations like global change.
- [ ] with `v:lua` we should rethink the entire vimL interface
- [ ] Simplify capability check in `client.request` (use a table or something)
- [ ] check race condition in `for_each_buffer_client`. Should probably just skip closed clients.

About specific callbacks:

- [ ] Diagnostic code guessing guifg from guibg is oddly specific. Diagnostic code should just use `LspDiagnostics{severity}` which should be defined `:hi default` and thus overridable by user by standard means. A mechanism for generating bright/dark colors should be separate from that, and invoked together by user if they want to.
- [ ] `update_tagstack` seems like something that should be primitive. Maybe using 'tagfunc' option sidesteps the entire tagstack issue?
- [ ] signature should highlight current param (I also would like it aligned to function start in code like vim-jedi does, but the info is not directly available from server)

**Comment by mcepl** [comment]
- [ ] I have still that code completion callback is not removing prefix. More testing on pyls is however somehow limited now for me, because something’s broken in pylint. I’ll get you back on it.

**Comment by mcepl** [comment]
- [ ] Explain how to write more complicate mappings. E.g., ``textDocument/rename``. Is this the right way?

```viml
function! LSPRename()
    let s:newName = input('Enter new name: ', expand('<cword>'))
    lua vim.lsp.buf_request(nil, 'textDocument/rename',vim.lsp.protocol.make_text_document_position_params({'newName': s:newName}))
endfunction

nnoremap <silent> <buffer> <F2> :call LSPRename()<CR>
```

**Comment by clason** [comment]
* [ ] Support `LocationLink` as well as `Location` for `definition` etc. if server supports it (allows defining a `peekDefinition` mapping that previews the target location in a float)

* [ ] Support multiple `Location[Link]`s (by putting them in the loclist?)

**Comment by clason** [comment]
* [ ] Support `filterText` for completion

**Comment by clason** [comment]
* [ ] Allow overriding the `symbolKind` and `completionItemKind` mappings in server configs (if you prefer `procedure` to `function`, say; it's particularly useful for "less typical" servers like texlab)

**Comment by clason** [comment]
* [ ] Provide a utility function to check if configured servers are running that can be used in the status line/airline/lightline to indicate if server is up or crashed.

**Comment by bfredl** [comment]
`v:lua` is now on master. In discussion with @norcalli on gitter we thought we should have a high-level interface for common requests in lua. If we have `vim.lsp.buf.hover()` wrapper, we can use `v:lua.vim.lsp.buf.hover()` (or in a mapping `<cmd>lua vim.lsp.buf.hover()<cr>` ), and delete `autoload/lsp.vim`. 

Also `set omnifunc=v:lua.vim.lsp.omnifunc` works already.

**Comment by jamestthompson3** [comment]
I've been having some issues with `omnifunc` re-inserting text. Minimal vimrc:
```viml
" minimal vimrc to repro lsp omnifunc issue

autocmd FileType rust setlocal omnifunc=v:lua.vim.lsp.omnifunc

set completeopt+=longest,noinsert,menuone,noselect
set completeopt-=preview

call lsp#add_filetype_config({
      \ 'filetype': 'rust',
      \ 'name': 'rls',
      \ 'cmd': 'rls',
      \ 'capabilities': {
      \   'clippy_preference': 'on',
      \   'all_targets': v:false,
      \   'build_on_save': v:true,
      \   'wait_to_build': 0
      \ }})
```

In a rust file if I go to type something like `form` and then hit `^X^O`, the omnifunc correctly suggests `format!(`, but when I select the option with `^N`, I get `formformat!(` I haven't run into this using other LSP clients.

**Comment by norcalli** [comment]
@jamestthompson3 @mcepl already reported this error above. It's a known issue and I'll be getting to improvements on the core on Monday. I've been focused on nvim-lsp while it's fresh in my mind so that I could ask LSP maintainers to help us fill in the database so that that can happen without my active involvement while I work on the core again.

**Comment by mcepl** [comment]
@norcalli The strange thing is that omnifunc (``Ctrl-X,Ctrl-O``) works correctly, only ``textDocument/completion`` function described above has problems. Weird.

**Comment by norcalli** [comment]
Another thing @bfredl and I discussed was that instead of builtin_callbacks, we would respect a global `vim.lsp.default_callbacks` to look for callbacks in the `vim.lsp.buf` functions. This is basically the same as overriding `vim.lsp.builtin_callbacks`, but it's more explicit. `default_callbacks` will be empty by default.

This means that users won't have access to our `builtin_callbacks` if they want to call those directly, though, so maybe we should keep them available under `default_callbacks`? It's questionable whether people will want to directly call our functions, especially if it was easy for them to just copy paste our code and use it themselves.

---

As for the `vim.lsp.buf`, we could skip specifying the prefix for `textDocument/` methods and specify it for everything else. i.e. `buf.rename()` vs `buf.workspace_configuration()`.

**Comment by norcalli** [comment]
@mcepl not that weird since they are implemented differently. Feel free to look at the implementation in builtin_callbacks.lua and debug it yourself or wait until someone else does it.

**Comment by bfredl** [comment]
> As for the vim.lsp.buf, we could skip specifying the prefix for textDocument/ methods and specify it for everything else. i.e. buf.rename() vs buf.workspace_configuration().

But I rather thought that `textDocument` "concept" would map to nvim "buf" terminology. `workspace` I would assume would be methods regarding not a specific buffer, so we would rather have a separate `lsp.wokspace` module if needed.

**Comment by norcalli** [comment]
Yeah that's why I deleted the comment, lol. I realized what I was saying was nonsense.

**Comment by agriffis** [comment]
autozimu/LanguageClient-neovim supports buffer formatting and range formatting. Is that under consideration?

**Comment by norcalli** [comment]
@agriffis everything is under consideration.

Before anyone else comes in here to do a feature request for something missing from core right now: It was merged with the bare minimum of features to be usable. **It will be improved in the coming days/weeks. It was only merged last week**

**Comment by teto** [comment]
LSP has evolved much since then. Let's stick to more focused issues.
