### ISSUE TITLE
:checkhealth : config/sanity checks

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1202]
followup of https://github.com/neovim/neovim/issues/1179#issuecomment-55994613

Now that we are beginning to depend on some "standard plugins", `nvim` should do a sanity check that verifies:
- [x] $VIMRUNTIME is accessible (i.e., readable by the current user) and valid. #7399
- [x] $VIM https://github.com/neovim/neovim/issues/1876#issuecomment-71468278 #7399
- [x] python provider https://github.com/neovim/neovim/issues/1760
- [x] TMUX settings https://github.com/neovim/neovim/issues/2035#issuecomment-76240819 , https://github.com/neovim/neovim/issues/2051#issuecomment-75937744
  - recommend 20ms `escape-time`. http://superuser.com/a/942704/114842
- [x] permission to read/write viminfo ~~https://github.com/neovim/neovim/issues/2774~~ 
  - Do this in `:checkhealth` (need `stdpath('shada')` or equivalent)
- [x] permission to read vimrc, etc. (`$VIM` ?) ~~https://github.com/neovim/neovim/issues/2774~~ 
- [x] `infocmp -L | grep key_backsp` _should_ report `key_backspace=\177` (ASCII BACKSPACE `127`,  `0x7f`, `0o177`) _not_ `^H`  (ASCII DELETE `8`, `0x08`, `0o10`). If the termcap/terminfo database reports `key_backspace=^H`, then when the user inputs `^H`, it is interpreted as `<backspace>`.
  - Vim's workaround for this mess: https://github.com/vim/vim/blob/master/src/term.c#L1845-L1864
- [x] advise `'nottimeout'` default https://github.com/neovim/neovim/issues/2454#issuecomment-230056129

**Comment by fwalch** [comment]
I'm sure that has already been discussed somewhere, but why do we use `$VIM(RUNTIME)` and not `$NVIM(RUNTIME)` (as with `.nvimrc` and `.nvim`)?

**Comment by justinmk** [comment]
backwards compatibility but now that you mention it I don't really know

**Comment by justinmk** [comment]
Backwards compatibility. The assumption is that many users will be using neovim to replace vim, rather than the interim situation we have currently, where users are flirting with neovim and still using vim. 

But now that you mention it, I can't think of a case where a script is setting VIMRUNTIME to anything that would be useful to neovim.

Also note that we (and Vim) still support things like `EXINIT` and `VIMINIT`.

**Comment by fwalch** [comment]
> I think the common case would be that it simply causes confusion.

I think so as well. Neovim's and Vim's runtime aren't interchangeable (anymore). Rename `$VIM` and `$VIMRUNTIME`, to `$NVIM..`, then?

> Also note that we (and Vim) still support things like EXINIT and VIMINIT.

Is there documentation on this? `:h $EXINIT` didn't bring up anything.

**Comment by justinmk** [comment]
try `:h EXINIT`

**Comment by fwalch** [comment]
> try :h EXINIT

D'oh.. of course. But why doesn't this have a dollar sign prefix, but e.g. `$VIM` has?

I don't want to derail this too much, but from #1153, if plugins depend on e.g. `$VIM`, we can't easily get rid of that. But can we *ignore* these values for Neovim itself (for discovering runtime, `.vimrc` etc), but still provide them to plugins (so that e.g. `:echo $VIM` outputs the contents/defaults of `$NVIM`)?

**Comment by justinmk** [comment]
I think sanity checks are a good compromise for now. If we switch to `NVIM*` now, we can't go back. But if we stick with `VIM*`, we can always add support for `NVIM*` later.

**Comment by toogley** [comment]
> http://pastie.org/10370245 

Link dead (502, bad gateway)
