### ISSUE TITLE
autoread (fswatch) tracking issue

### ISSUE THREAD

**Issue by BK1603** [neovim/neovim#12605]
## Current Plan
- Use a new option `fswatch` that takes three values `notify` `autolaod` and `off`. 
    - If `notify` is set we notify the user about changes.
    - If `autoload` is set we automatically update the files. (For logs.)
    - `off`
We can have these options set per file/filetype via `after/<LANG>,vim` That way we can leverage the existing filetype plugin.
- For #1785, I am thinking of watching the directory that is supposed to contain the file. That way we can detect if a file was created and load it. 
- For [this](https://github.com/neovim/neovim/issues/1380#issuecomment-77283133) comment, stating that neovim should detect when a file was moved and reflect the changes accordingly, and write to a new location, I couldn't think of anything too reliable. If we watch directories, what is the upper limit? We can't watch the entire filesystem with all the subdirectories in it, and the user can always move a file to anywhere. Maybe we can watch the root directory of a project. (Eg, git repo) But then only the files inside the project will be covered. And that too might get too much in terms of resources. I don't know how atom does it. I will try and find it out. 
- For the fallback mechanism, the only way that we have right now is to run both (polling and fs notification) watchers simultaneously and see which receives the changes first. And use that. 

**EDIT:** A point that I missed, what I am thinking of is only giving notificatinos for buffer that is being currently edited, so that we don't break the workflow of a user editing something by notifying him about a change made in a buffer that isn't even visible. What are everyone else's thoughts about this? We can show notifications for the buffer that is active and queue the rest. 

Do suggest some improvements to this.
The current implementation resides at #12593.

**Comment by teto** [comment]
relevant comments on the design https://github.com/neovim/neovim/pull/12593#issuecomment-667654125

**Comment by BK1603** [comment]
As mentioned in the last comment of the original PR (https://github.com/neovim/neovim/pull/12593) I am thinking of splitting this issue into 3 separate PRs:

- [ ] Libuv based autoread. (https://github.com/neovim/neovim/pull/20801)
- [ ] New option to enable or disable filewatching itself. 
- [ ] A way of showing diff when we prompt the user for an update.

@justinmk, point number 2 is up for debate. For now I have dropped the additional option. 

cc @teto @justinmk

**Comment by justinmk** [comment]
>  New option to enable or disable filewatching itself.

Why is a new option needed? 'autoread' already is that option.

> A way of showing diff when we prompt the user for an update.

Breaking this out into a separate PR is a good idea!

**Comment by BK1603** [comment]
I am thinking along the lines that what we are doing is changing the actual behavior of autoread. And this might change any tools/plugins that rely on this behavior. 
So maybe giving an option, to switch back to how it used to work helps?

But I do remember you suggesting that we can ask users to change lua configurations if they do not want this. Do we want to go ahead with that?
@justinmk

**Comment by justinmk** [comment]
> only give notifications for buffer that is being currently edited, so that we don't break the workflow of a user editing something by notifying him about a change made in a buffer that isn't even visible

By "notification" do you mean the warning prompt? https://github.com/neovim/neovim/issues/1785

Per `:help 'autoread'`, that prompt should only appear if there are unsaved changes. So, there is rarely "workflow breakage". For cases where a file is often updated on-disk, user can `:setlocal noautoread` on that particular file to avoid a noisy prompt.

In general I think it makes sense to load all buffers (including hidden/non-visible buffers) so that plugins and commands will see the updated buffer contents. The user has plenty of control over this, via 'hidden', 'bufhidden' and buffer-local 'autoread'.

**Comment by justinmk** [comment]
# Status

- [ ] [#22405](https://github.com/neovim/neovim/pull/22405) introduced `_watch.lua`. Either re-use that for 'autoread' or replace it with whatever we implemented for 'autoread'.
- [ ] Libuv based autoread (overlaps with `_watch.lua` (see above)?). (https://github.com/neovim/neovim/pull/20801)
- [ ] User can see a diff when we prompt the user for an update?
- [ ] https://github.com/neovim/neovim/pull/12503
- ~~New option to enable or disable filewatching itself.~~

**Comment by justinmk** [comment]
Merged with https://github.com/neovim/neovim/issues/1380#issuecomment-1946115753
