### ISSUE TITLE
release checklist 0.7

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#15798]
(previous: https://github.com/neovim/neovim/issues/11023)

## Pre-release (early)

- [x] Runtime updates
- [x] Bump deps in `third-party/CMakeLists.txt` 
  - [x] libuv
  - [x] luajit
  - [x] luv
  - [x] luarocks
  - [x] treesitter
  - [x] libvterm (0.2 upgrade bumped to 0.8)
- [x] Bump luarocks packages [example](https://github.com/neovim/neovim/pull/8069/files)
  - [x] [lua-client](https://github.com/justinmk/neovim/blob/924e8e4f2d88ee5c45e521e9f758b7c9f247a011/third-party/cmake/BuildLuarocks.cmake#L220-L225)
- [ ] Bump neovim-qt in `third-party/CMakeLists.txt` [example](https://github.com/neovim/neovim/pull/14514)

## Pre-release

- [x] Run `scripts/release.sh`

## Post-release

- [x] (For non-maintenance release) Remove the [needs-backport](https://github.com/neovim/neovim/pulls?q=is%3Aopen+is%3Apr+label%3Astatus%3Aneeds-backport) label from all PRs
- [x] For major releases, create a new `release-x.y` branch.
    - **Bump the version in CMakeLists.txt** and set `NVIM_VERSION_PRERELEASE`.
- [x] Review [status:revisit-at-release issues](https://github.com/neovim/neovim/labels/status:revisit-at-release)
- [x] Document [breaking changes](https://github.com/neovim/neovim/wiki/Following-HEAD), if any
- [x] Newsletter https://github.com/neovim/neovim.github.io
