### ISSUE TITLE
Missing Vim patches

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#1745]
Some patches don't have tags, so they have not been ported yet. It's mostly runtime updates (which will be hard to review).

- [x] 4c08173b8b952f9d0bd66b2f067bdbb3fce43fd7 (already in as `utf8_spec.lua`)
- [x] 1e8ebf870720e7b671f98f22d653009826304c4f (runtime update): #1744
- [x] 353442863d8558dc89d35ef349b60ebb2e38de0e (was just forgotten update of version.c for 7.4.415)
- [x] babc6a1d4c270e3a8004dad9d3b3648f067bdfde (runtime update): #1759
- [x] 6921742f396a4abd21d7f69843b804ca0b96059c (runtime update): #1772
- [x] 37c24033b2601a4a0953970a0ec85d5537101915 (runtime update): #1772
- [x] 47b1887483da0bc33d26a3e8d89973d76c9f39ef (runtime update): #1852
- [x] bd18da914be9d43a70713f6af02770a0d3280159 (runtime update): #1853
- [x] 31f7581068a9c3119e3bd2cd74160eb8282c3c6e (runtime, tutor, translations update): #1871
- [x] 6a598be6d4e80c0112a3cbd4a8c00ab0c9e22e6e (test for 7.4.487): #1754
- [ ] 4abac79c0b7ae7aac0cb32d9930e155de628b63f (runtime update)
- [ ] c5d53d4c3e2e24e23fc4272bf91be3c031ccb598 (runtime update)
- [ ] 10a119b05204330961dce6a2f306164b4a78fde8 (translations update)
- [ ] f654ad95fd4e25e014dda71963b9745a4bf5f83b (runtime update)
- [x] 1e6d87a36dcdca231721dde8cbbc26610fb3df27 (tests for 7.4.530): #1793
- [ ] 5d89d9b40499059e1a64dc35fbae94313fba0098 (runtime update)
- [x] 750a6986aa86a2bb3346631a353913b899d86748 (tests for 7.4.549): #1738
- [ ] 0550be8fc7f6abedf6140a2e86eac693788246ee (runtime update)
- [ ] 11d78e58a487471e13ecb5223b75249cd7e949d5 (runtime update)

(List last updated for 7.4.567).

Command used to get this list:

```
hg log --removed --template='{if(startswith("Added tag", firstline(desc)), "{latesttag}\n", "{if(startswith(\"updated for version\", firstline(desc)), \"\", \"{node}\n\")}")}' -r tip:v7-4-161
```

Any ideas on how to integrate this into the vim-patch report/version.c/... so it can be tracked?

**Comment by fmoralesc** [comment]
I'm adding `1e6d87a36dcdca231721dde8cbbc26610fb3df27` to #1793.

**Comment by fwalch** [comment]
As `vim-patch.sh --list` can now be used to list all missing commits, I'll close this.
