### ISSUE TITLE
release checklist 0.8

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#18374]
(previous: https://github.com/neovim/neovim/issues/15798)

- [Release guidelines](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#release-policy)
- [Dependencies](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies)

## Pre-release (early)

- [x] Runtime updates
- [x] run `scripts/download-unicode-files.sh`
- [ ] Bump deps in `third-party/CMakeLists.txt`
    - [ ] run `scripts/bump_deps.lua`
    - [x] libuv
    - [ ] luajit
    - [x] luv
    - [ ] luarocks
    - [x] treesitter
    - [x] libvterm (0.3 stable)
- [x] Update wintools.zip #14078
- [x] Bump luarocks packages [example](https://github.com/neovim/neovim/pull/8069/files)
  - [x] [lua-client](https://github.com/justinmk/neovim/blob/924e8e4f2d88ee5c45e521e9f758b7c9f247a011/third-party/cmake/BuildLuarocks.cmake#L220-L225)
- [x] Bump neovim-qt in `third-party/CMakeLists.txt` [example](https://github.com/neovim/neovim/pull/14514)

## Pre-release

- [x] Run `scripts/release.sh`

## Post-release

- [x] For major releases, create a new `release-x.y` branch.
    - **Bump the version in CMakeLists.txt** and set `NVIM_VERSION_PRERELEASE`.
- [ ] Review [status:revisit-at-release issues](https://github.com/neovim/neovim/labels/status:revisit-at-release)
- [x] Document [breaking changes](https://github.com/neovim/neovim/wiki/Following-HEAD), if any
- [ ] Newsletter https://github.com/neovim/neovim.github.io

**Comment by dundargoc** [comment]
I'd like to add another point (both for this release and for each upcoming release): remove deprecated functions/features before release. The following functions have been marked to be removed for neovim 0.8:

- `lsp.diagnostic.disable`
- `lsp.diagnostic.enable`
- `lsp.diagnostic.get_all`
- `lsp.diagnostic.get_count`
- `lsp.diagnostic.get_next_pos`
- `lsp.diagnostic.get_next`
- `lsp.diagnostic.get_prev_pos`
- `lsp.diagnostic.get_prev`
- `lsp.diagnostic.get_virtual_text_chunks_for_line`
- `lsp.diagnostic.get`
- `lsp.diagnostic.goto_next`
- `lsp.diagnostic.goto_prev`
- `lsp.diagnostic.redraw`
- `lsp.diagnostic.save`
- `lsp.diagnostic.set_loclist`
- `lsp.diagnostic.set_qflist`
- `lsp.diagnostic.set_signs`
- `lsp.diagnostic.set_underline`
- `lsp.diagnostic.set_virtual_text`
- `lsp.diagnostic.show_line_diagnostics`
- `lsp.diagnostic.show_position_diagnostics`

The following functions should also be removed for 0.8 since they belong to the same group of changes @gpanders made. I forgot to "officially" deprecate these in my PR :). I'll fix that right now.

- `lsp.util.set_qflist`
- `lsp.util.set_loclist`
- `lsp.buf_get_clients`

**Comment by gpanders** [comment]
I would not remove lsp.buf_get_clients yet. We can vim.deprecate() it in 0.8 and remove it in 0.9. But it should be deprecated in a release before being removed so that users following stable have a chance to transition.

**Comment by clason** [comment]
Reminder to self: don't forget to 
* update libvterm to 0.3
* bump minimum version to 0.3
* remove compat `#ifdef` from `terminal.c`

**Comment by bfredl** [comment]
> update libvterm to 0.3
> bump minimum version to 0.3
> remove compat #ifdef from terminal.c

For future reference: this has been done prior to 0.8.

**Comment by justinmk** [comment]
update win32tools and neovim-qt:

- https://github.com/neovim/neovim/pull/20411
