### ISSUE TITLE
Roadmap to graduating `filetype.lua`

### ISSUE THREAD

**Issue by clason** [neovim/neovim#18604]
**Goal:** Make `filetype.lua` detection the default for Neovim 0.8.

**Roadmap:**

* [x] port remaining patterns from `filetype.vim` to `filetype.lua` ([rough list](https://github.com/neovim/neovim/files/8806503/ftlua.txt)) #18219 #18814 #19218 
* [x] port remaining functions from `dist#ft.vim` to `filetype/detect.lua`  #18247, #18430, #18623
* [x] refactor `vim.filetype.match` to return the detected filetype instead of setting it (see #18241) #18894
* [x] refactor `filetype.lua` to set buffer variables in `vim.filetype.match()` (and allow opting out) #18894
* [x] refactor `filetype.lua` and `detect.lua` to have a clearer separation of concerns; better sorting https://github.com/neovim/neovim/pull/18813
* [x] refactor `filetype.match()` to allow matching on buffer, filename or contents #18895
* [x] port `scripts.vim` to Lua #18710
* ~~[ ] support (builtin) globs in `nvim__get_runtime` (so Lua and Vim `ftdetect` files are loaded in the correct order; see #18426)~~ (not needed for parity)
* [x] toggle defaults for `g:do_filetype_lua` and `g:did_load_filetypes` #19216
* [x] 🥳

**Comment by clason** [comment]
`filetype.lua` is now enabled by default (early adopters should make sure to remove `vim.g.did_load_filetypes = 0` from their config!).

Huge shoutout to @smjonas and @kessejones for their diligent and patient efforts in porting all the complicated filetype patterns and detection functions and dealing with the edge cases that kept popping up! 🎉

**Comment by ignamartinoli** [comment]
Can I remove `g.do_filetype_lua = 1` too?

**Comment by clason** [comment]
Yes (it's ignored, though, so you don't _have_ to, unlike `g:did_load_filetypes`).

**Comment by ignamartinoli** [comment]
Thanks! And congrats for the achievement to all involved, I came back daily to this post to see its progress

**Comment by clason** [comment]
For those coming here from Twitter (and not subscribed to the "Following HEAD" issue): If you were using `filetype.lua` before, you now **must remove** `g:did_load_filetypes = 0` from your `init.vim` (which again follows upstream use to disable _all_ filetype detection).
