### ISSUE TITLE
Tracking issue: treesitter highlighting

### ISSUE THREAD

**Issue by clason** [neovim/neovim#19350]
**Goal:** Enable out-of-the-box `treesitter` highlighting of core languages (Lua, Vimscript) for Neovim 0.8

**Roadmap:** 

* [x] Replace static capture-to-highlight group table with automatic mapping (hierarchical, e.g., `@keyword.special` from Lua gets mapped to `TSKeywordSpecialLua`, with fallback to `TSKeywordSpecial` or `TSKeyword` if the more specific groups don't exist #19931
* [x] Include Lua and  Viml parsers in build process (similar to C parser) #15391
* [x] Ship parsers and queries in runtime  #15391
* [x] Upstream basic highlighting functionality from `nvim-treesitter`  #15391
* [x] Change query handling to give same precedence as for parsers (config > plugins > runtime), with explicit extending via  modelines (needs documentation!) #20104 #20117
* [x] Upstream utility functions from `nvim-treesitter` and `nvim-treesitter-playground` #19946 #20093
* [ ] ~~Upstream predicates and directives from `nvim-treesitter`; refactor metadata handling to be more generic?~~ (bumped to 0.9)
* [x] Upstream https://github.com/lewis6991/spellsitter.nvim (enabled automatically if treesitter highlighting is enabled for a language) #19351
* [x] Update and polish `vim.treesitter` docs #20142
* [x] 🥳

**Comment by clason** [comment]
# Proposal for highlight groups:

Create a new set of hierarchical groups that are mapped **losslessly** from captures (e.g., `@keyword.special`), with sane fallback to defaults.

1. Implicitly generate a highlight group for every capture, e.g., `TS.keyword.special` that can be mapped directly (but isn’t necessary by default)
2. Groups are implicitly language-specific, e.g., `TS.keyword.special.lua`
3. If not mapped, they successively fall back to the top level, e.g., `TS.keyword`
4. Provide a set of top-level (and possibly _some_ second-level?) groups that are linked by default to suitable standard Vim groups and/or are mapped by the default and bundled color schemes.  These groups need not derive from the set of standard Vim groups; it might be better to provide a small(!) number of different sets for different types of languages (with overlap), like "imperative languages" (C, Lua, Python, ...), "markup languages" (Markdown, LaTeX, HTML), "data representation languages" (JSON, regex, ...).
5. Languages are free to extend the capture hierarchy, e.g., `@snowflake.superfancy`, with the clear understanding that these won’t be highlighted unless mapped by custom colorschemes or plugins. (This also allows optional highlighting that is disabled by default.)

**Comment by justinmk** [comment]
> 1. Implicitly generate a highlight group for every capture, e.g., `TS.keyword.special`

With https://github.com/neovim/neovim/pull/19830 would we generate the identical names (`@keyword.special`) instead?

**Comment by clason** [comment]
Yes, that's exactly the idea (if deemed acceptable) of the last sentence.

**Comment by justinmk** [comment]
Proposal LGTM except this part:

> These groups need not derive from the set of standard Vim groups; it might be better to provide a small(!) number of different sets for different types of languages (with overlap), like "imperative languages" (C, Lua, Python, ...), "markup languages" (Markdown, LaTeX, HTML), "data representation languages" (JSON, regex, ...).

Can that be postponed to a "phase 2" discussion?

**Comment by clason** [comment]
> Can that be postponed to a "phase 2" discussion? Just thinking this might be an expensive discussion.

Hmm, I worry about lock-in in this case. If we don't do it at the same time (or in close coordination), it'll be deemed as "too breaking" and never actually happen. In this case I prefer a clear decision against now to avoid wasting time on this.

Of course, we don't have to discuss this into the fine details for the purpose of this tracking; it's enough to have a general plan (yay or nay, and a rough idea of the layout we want).

**Comment by clason** [comment]
*(Changed my mind.)*

Sure; none of the technical details of the other points depends on this decision. I merely included it here in case we wanted to rip the band-aid off in one go.
