### ISSUE TITLE
release checklist 0.9

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#20434]
(previous: https://github.com/neovim/neovim/issues/18374)

- [Release guidelines](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#release-policy)
- [Dependencies](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies)

# Pre-release (early)

- [x] Runtime updates
- [x] Query updates from nvim-treesitter
- [x] run `scripts/download-unicode-files.sh`
- [x] Bump deps in `third-party/CMakeLists.txt`
    - [x] run `scripts/bump_deps.lua` (luajit, luv, libuv, treesitter)
    - [x] treesitter parsers (C, Lua, Viml, Vimdoc, Query)
    - [x] luarocks #22680 
    - [x] libvterm
    - [x] msgpack
- [x] Bump [luarocks packages](https://github.com/neovim/neovim/blob/a0292b4e5f106482edc5623eef85aa48e2e55bb7/cmake.deps/cmake/BuildLuarocks.cmake#L104) ([example](https://github.com/neovim/neovim/pull/8069/files)) #22680 
- [x] Bump neovim-qt in `third-party/CMakeLists.txt` ([example](#14514))
- [x] Update (individual) wintools #14078

# Pre-release

- [x] Remove deprecated functions marked for 0.9 (#22627)
- [x] Clean up `news.txt` (sorting, phrasing)
- [x] Remove the `.deb` from the release script (#22773)
- [x] Run `scripts/release.sh`

# Post-release

- [x] For major releases, create a new `release-x.y` branch.
    - **Bump the version in CMakeLists.txt** and set `NVIM_VERSION_PRERELEASE`.
- [x] Review [status:revisit-at-release issues](https://github.com/neovim/neovim/labels/status:revisit-at-release)
- [x] Move `news.txt` to `news-0.9.txt` (and remove/update tags!), add blank `news.txt`
- [ ] Newsletter https://github.com/neovim/neovim.github.io
- [ ] Remove deprecated:
    - [ ] remove support for old treesitter query injection format [ref](#22518)

**Comment by clason** [comment]
copy `news.txt` to `news-0.8.txt` and start a new one

**Comment by dundargoc** [comment]
We can remove `pkgconfig` and `libtool` as build dependencies from the wiki after release.

**Comment by justinmk** [comment]
nvim-qt tagged a release so we can bump it now: https://github.com/equalsraf/win32yank/issues/19

**Comment by dundargoc** [comment]
@justinmk on "Update wintools.zip": can we make this process simpler in some way? Compared to bumping other dependencies this is slighty more involved. It's not a big problem of course, but reducing busywork is always nice. Especially during releases when things tend to be more hectic.

**Comment by justinmk** [comment]
> on "Update wintools.zip": can we make this process simpler in some way? Compared to bumping other dependencies this is slighty more involved

Certainly. The big zip is a historical accident: AFAIR the old download helper expected a zip. 
- If the cmake download helper can just download binaries, then we can push the binaries directly to https://github.com/neovim/deps .
-  in the case of `cat` that could be a `cat.c` source file that we build instead of including it as a binary
    - also for `tee` ?

**Comment by linrongbin16** [comment]
> > Do you know where the `cat` and `tee` source code is?
> 
> BSD is a good source:
> 
> * https://github.com/openbsd/src/blob/master/usr.bin/tee/tee.c
> * https://github.com/openbsd/src/blob/master/bin/cat/cat.c

GNU coreutils also has the most popular cat/tee implementation: [coreutils/src](https://github.com/coreutils/coreutils/tree/master/src)

**Comment by dundargoc** [comment]
> GNU coreutils also has the cat/tee implementation: [coreutils/src](https://github.com/coreutils/coreutils/tree/master/src

Hmm, the GNU implementations have around 3x more code for some reason. BSD implementations seem simpler.

**Comment by dundargoc** [comment]
Random idea: could we use cmake for cat? Cmake had command-line mode `-E` that is cross-platform. So cat would be `cmake -E cat <file>`

https://cmake.org/cmake/help/v3.26/manual/cmake.1.html#cmdoption-cmake-E-arg-cat

**Comment by clason** [comment]
That would raise the minimal version from 3.10 to 3.18, wouldn't it?

**Comment by dundargoc** [comment]
Only for testing, but fair.

**Comment by dundargoc** [comment]
`curl` is shipped by default on Windows 10, version 1803 and later: https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/

**Comment by nosvagor** [comment]
> - [x] Query updates from nvim-treesitter
 
 Where can I find more info about these updates?
