### ISSUE TITLE
[Tracking issue] docs: fix treesitter parsing errors

### ISSUE THREAD

**Issue by clason** [neovim/neovim#21587]
As our documentation at https://neovim.io/doc/user/ is generated from our vimdoc help files via treesitter, (some) help files taken from vim/vim that use ambiguous syntax that is not (easily) parseable with https://github.com/neovim/tree-sitter-vimdoc show up as visible errors in the generated HTML.

In a nutshell, the problems are from

* using single quotes for actual quoting (which conflict with option names) -> use double quotes (preferable) or backticks (if necessary, e.g., if the quote involves `"`) instead
* using ASCII tables, whose vertical bars conflict with tag names -> put tables into code blocks
* using ASCII underline for h3 headings -> use proper ------ section delimiters.

Unless I missed some, the affected files are

* [X] api.txt (1)
* [x] builtin.txt (11)
* [x] editing.txt (3)
* [X] eval.txt (3)
* [x] ft_sql.txt (3)
* [X] gui.txt (3)
* [x] hebrew.txt (2)
* [X] helphelp.txt (1)
* [x] indent.txt (11)
* [X] insert.txt (4)
* [x] intro.txt (13)
* [X] lua.txt (2)
* [X] luvref.txt (2)
* [X] map.txt (1)
* [x] mbyte.txt (2)
* [X] motion.txt (3)
* [X] options.txt (9)
* [x] pi_netrw.txt (1)
* [X] pi_spec.txt (4)
* [x] quickfix.txt (3)
* [x] rileft.txt (1)
* [X] starting.txt (3)
* [X] syntax.txt (2)
* [X] tagsrch.txt (4)
* [X] tips.txt (1)
* [x] userfunc.txt (1)
* [x] usr_*.txt (02,05,08,10,20,21,25,29,30,32,40,42)
* [X] windows.txt (2)

The plan is to fix these in batches (of which the first is #21570, which fixes the ticked files). After that, an enterprising soul may try to see if these changes would be acceptable for vim/vim (which would be preferable to avoid conflicts and/or regressions down the line).

**Comment by zeertzjq** [comment]
> these are strings and backticks are for commands.

https://github.com/vim/vim/pull/11228

**Comment by clason** [comment]
Pity, but using double quotes instead of single quotes will already fix many (if not all) of the parsing errors; I'll reserve backticks then only for those cases that need it (in particular for strings involving a double quote itself).
