### ISSUE TITLE
Tracking issue: spring-cleaning the runtime

### ISSUE THREAD

**Issue by clason** [neovim/neovim#22980]
### Problem

We have inherited (and still actively maintain by porting updates to) Vim's runtime files, a lot of which are very useful and part of Neovim's value proposition. However, some of them have aged less well and are obsolete, broken, or otherwise useless (either due to divergent Neovim features or upstream neglect). Keeping these files around makes it harder to focus our limited maintenance budget and sets wrong expectations (that these functions are working and useful in Neovim). We should remove them or, if necessary, replace them with new, working, implementations:
* [x] Vimballs: obsolete with packages #22402
* [x] `:CheckHealth`: obsolete with :checkhealth #23031
* [x] `bugreport.vim`: obsolete with :checkhealth #23053
* [ ] `macros`: compatibility shims for `packadd`, or scripts that replicate standard Neovim features (`editexisting.vim`, `less.vim`)
* [ ] `tools`: `check_colors.vim` (broken on Neovim), ~`emoji_list.vim`~ (actually a Lua script, move to `lua`?)
* [ ] `macmap.vim` `mswin.vim` (different defaults)
* [ ] `pack/dist/opt`: `swapmouse` (really?), `shellmenu` (targets gVim?)
* [ ] ...

### Expected behavior

Eternal sunshine of the spotless runtime.

---

## Proposal

Consolidate all "one-off" scripts we want to keep to a new `runtime/scripts` directory (making sure to update the docs accordingly). Err on the side of keeping stuff for now.

**Comment by craigmac** [comment]
How about our own ftplugin/lua.lua, or an after/ftplugin/lua.lua (I'd prefer this) so we can tailor lua experience with neovim specific things in mind, things that upstream won't accept in their ftplugin/lua.vim, like making K work better with vim.api.nvim_

**Comment by dundargoc** [comment]
You can already put lua files in `ftplugin` and `after/ftplugin` right now I think? Maybe I misunderstood something.

**Comment by zeertzjq** [comment]
- When removing a runtime file, also remove the reference to it from docs.
- Please don't remove `emoji_list.vim`. What's the cost of keeping it?

**Comment by clason** [comment]
> What's the cost of keeping it?

Gonna flip that on you: why do you care?

**Comment by zeertzjq** [comment]
> > What's the cost of keeping it?
> 
> Gonna flip that on you: why do you care?

It can be used to check if Nvim and host terminal's character width assumptions match.

**Comment by clason** [comment]
Shouldn't that be a health check then?

**Comment by zeertzjq** [comment]
The user needs to examine the result manually.

**Comment by craigmac** [comment]
> You can already put lua files in `ftplugin` and `after/ftplugin` right now I think? Maybe I misunderstood something.

in your personal runtime, yes. I'm talking about in the shipped runtime so everyone could benefit

**Comment by zeertzjq** [comment]
> macros

Related: #2918, although rust.vim now recommends `packadd matchit` instead of automatically sourcing `matchit.vim`.
