### ISSUE TITLE
release checklist 0.10

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#23235]
(previous: https://github.com/neovim/neovim/issues/20434)

- [Release guidelines](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#release-policy)
- [Dependencies](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies)

# Blocking issues

- https://github.com/neovim/neovim/pull/28227
- https://github.com/neovim/neovim/pull/26138
- https://github.com/neovim/neovim/pull/28450
- https://github.com/neovim/neovim/pull/28440
- https://github.com/neovim/neovim/issues/27953
- https://github.com/neovim/neovim/issues/28548
- https://github.com/neovim/neovim/pull/28432
- (partial) https://github.com/neovim/neovim/issues/24572

# Pre-release (early)

- [x] run `scripts/download-unicode-files.sh`
- [x] Bump deps in [cmake.deps/deps.txt](https://github.com/neovim/neovim/blob/master/cmake.deps/deps.txt)
    - [x] run `scripts/bump_deps.lua` (luajit, luv, libuv, treesitter)
    - [x] treesitter parsers (C, Lua, Viml, Vimdoc, Query)
        - [x] update queries from nvim-treesitter
    - [x] lpeg (also in `neovim/deps`)
    - [x] libvterm (also in `neovim/deps`)
    - [x] msgpack
    - [x] [wintools](https://github.com/neovim/neovim/blob/9319d97679053a219b1701d70abce414d0f6a8b0/cmake.deps/deps.txt#L28-L36)
- [x] check s930x CI logs for errors pertaining to big-endian systems
    - [run1](https://github.com/neovim/neovim/actions/runs/9062490238/job/24896468103?pr=28730) [run2](https://github.com/neovim/neovim/actions/runs/9062490238/job/24896468325?pr=28730) (result: no new regressions)

# Pre-release

- [x] Remove deprecated functions marked for this release
    - [x] `Iter:nextback() Iter:peekback() Iter:skipback() Iter:nthback(n)`
    - [x] https://github.com/neovim/neovim/pull/28725
- [x] Clean up `news.txt` (sorting, [phrasing](https://www.youtube.com/watch?v=Qs8Gohi1e04))
- [x] Merge `nvim.appdata.xml` changes from the maintenance branch. https://github.com/neovim/neovim/pull/28769
- [x] Run `scripts/release.sh`

# Post-release

- [ ] For major releases, create a new `release-x.y` branch.
    - **Bump the version in CMakeLists.txt** and set `NVIM_VERSION_PRERELEASE`.
- [x] Move `news.txt` to `news-x.y.txt` (and remove/update tags!). Recreate `news.txt` with "skeleton" from the old one.
- [ ] Review [revisit-at-release issues](https://github.com/neovim/neovim/labels/revisit-at-release)
- [ ] Newsletter https://github.com/neovim/neovim.github.io
- [ ] Update [GitHub Sponsors page](https://github.com/sponsors/neovim) (what was done, what is planned)
- [ ] Update [roadmap](https://neovim.io/roadmap/)
- [x] Remove deprecated:
    - [x] remove support for old treesitter query injection format [ref](https://github.com/neovim/neovim/pull/22518#issuecomment-1460836002)

# Merge these after release

- https://github.com/neovim/neovim/pull/28416
- https://github.com/neovim/neovim/pull/28487

**Comment by XVilka** [comment]
It probably makes sense to extend the checklist with "Update GitHub Sponsors page: https://github.com/sponsors/neovim" since you have a description of what has been done and what is planned for the next release.
