### ISSUE TITLE
Options refactor roadmap

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#25672]
### Problem

The Neovim options code is an incomprehensible mess filled with code duplication, special logic for every option, multiple code paths for the same thing, lack of generalization, etc. This makes Neovim options difficult to maintain, and even more difficult to extend, which has been a blocker towards the addition of new option types (e.g. Callback, Array, Dictionary).

### Expected behavior

This is a roadmap for refactoring Neovim options to be more extensible and maintainable. This is not an absolutely concrete roadmap and each item is subject to change, further additions and deletions may also be made at any time.

- [ ] Unify interfaces for setting options.
  - [x] Implement a single type to represent any option value. This is done in #23850 using `OptVal`.
  - [x] Unify `do_set_option_value` and `set_option_value` codepaths. Done in #25394.
  - [ ] Unify interfaces for setting number, boolean and string options.
    - [x] Unify interfaces for setting number and boolean options. Implemented in #25394.
    - [ ] Unify interfaces for setting number/boolean and string options.
    - [ ] Unify separate interfaces for setting string options (e.g. `set_string_option_direct`, `set_string_option_global`, etc.)
    - [ ] Remove certain functions specific to string options (e.g. `free_string_option`, `clear_string_option`) and replace them with something more general.
  - [ ] Use `OptVal` for option `def_val`.
- [ ] Check if `OPT_FREE` is necessary and remove it if it isn't.
- [ ] Use reference counted strings for string options.
- [ ] Allow certain options to have multiple types. Ref: #24045
- [ ] Use a separate option type (`kOptValTypeUnset`?) to indicate an unset local value for a global-local option, instead of using arbitrary values for each option. This also would mean that boolean options no longer need to be represented using tri-states and instead can be actual booleans.
- [ ] Use `bool` type for boolean option variables, instead of `int`.
- [ ] Fix the behavior of `winbar` and make it possible to unset winbar for a single window.
- [ ] Convert `P_FUNC` to a separate option type for callback options, instead of having them be shoehorned into string options.
- [ ] Add support for Array and Dictionary options.
- [ ] Convert all list-like or map-like string options to Array / Dictionary options.
- [ ] Add a dict-based configuration format for complicated options such as `winbar`, `tabline`, `statusline`, etc.

**Comment by famiu** [comment]
CC: @justinmk @bfredl

**Comment by justinmk** [comment]
Except for the "scopes redesign", this refactor is complete. We can keep open https://github.com/neovim/neovim/issues/29314 to track that.

- `Object` is used as the structured representation.
- [Array/Dict options](https://github.com/neovim/neovim/issues/32139#issuecomment-5083530419) are defined (and auto-validated) as `schema` in `options.lua`.
    - This generates no-alloc keysets (`opt_keyset`).
    - https://github.com/neovim/neovim/pull/40924
- "func"/"expr" options: https://github.com/neovim/neovim/pull/41065
