### ISSUE TITLE
Default color scheme follow up

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#26369]
This is a tracking/roadmap issue for follow-up work after #26334. It is meant more about discussing *what* should be done with more details inside dedicated issues (if necessary).

------

- [x] Tweak default highlight groups based on the feedback. I am not sure it is a good idea to deviate too much from "be minimal and green-blue" requirement, but at least concious consideration should be done here. Some early feedback:
    <details><summary>Issues addressed in #26540</summary>

    - Consider changing base lightness values of grey colors to increase contrast. Maybe something like `{ 4, 8, 16, 32 }` (*very* high contrast) or `{ 5, 10, 20, 30 }` (slightly less increase in contrast for `Normal` but significantly more for `Comment`) can work.
    
        It also seems important to not lean too much into "high contrast" territory, as it is also not an average good UI. Just enough to make it accessible (even more than now) should be good.

    - Use 0-15 colors for `cterm` attributes after #26407 is merged. This allows both to have good experience with `nvim --clean` for new users and respect terminal colors for anyone who wants/needs it. See #26389.
 
    - Right now `Special` highlight group is the same as Normal. It is a relatively highly linked highlight group, but so is `Identifier`. As there are only cyan and blue available (green is for strings) I decided to leave `Special` unhighlighted. It can be made magenta or bold blue/cyan; both don't look quite minimal to me, though.
    
        Or just cyan as it might be better to be highlighted as *something* than not be highlighted at all (as per [this comment](https://github.com/neovim/neovim/issues/26369#issuecomment-1837516465)).

    - Use any attribute only when they are intended to be different. Example: revert `DiagnosticFloating*` back to link to `Diagnostic*`. Also maybe all "base" syntax groups (`Constant`, `Statement`, `PreProc`, `Type`) and similar that are intended to "not be extra highlighted".

    - Make `EndOfBuffer` different from `Whitespace` as per [this comment](https://github.com/neovim/neovim/issues/21694#issuecomment-1575756133).
    - Make `QuickFixLine` blue or cyan (as per [this comment](https://github.com/neovim/neovim/issues/26369#issuecomment-1837497703)).
    - Maybe make `Search`, `CurSearch`, and `IncSearch` be actually different. Ideas: make `CurSearch` have bold foreground; make `CurSearch` be the `Search` from other dark/light variant (so for dark it would have `NvimLightYellow` as background and `NvimDarkGrey1` as foreground).

    - Consider removing [these lines](https://github.com/neovim/neovim/blob/66f1563c7a48d76f99c89e32de030e57af2abfb4/runtime/colors/default.vim#L7-L11) from 'runtime/colors/default.vim' as they don't do in Neovim what they claim to do. They reset `'bg'` back to default which is 'dark'. This breaks if there is a `set bg=light` followed by `:colorscheme default`.

    - Consider reverting `WinSeparator` to depend on `VertSplit`. It might be better for Vim's color scheme compatibility. But since the latter was deprecated in 0.8.0, it seems to be a good opportunity to pull the plug now.

    - Update 'runtime/colors/vim.vim' for `Visual` to have `cterm` values. See #26468.
    </details>

    - Address statusline usability. See #26921.
    - Address `IncSearch` behavior. See #26922.

    - <s> Don't create cleared highlight groups (as now are "core" syntax groups, `Statement`, `@variable`, etc.). This doesn't quite work with `@`-highlight groups due to their fallback. Example: cleared groups fall back to `@text.literal.block.markdown` which falls back to `@text.literal` which is linked to `Comment`.
        Solution: define those explicitly to have `Normal` foreground and no background. </s>
        Addressed in #27188.

- [x] <s>Add proper terminal colors for built-in terminal. Right now they are inherited from terminal emulator (except background and foreground), but it doesn't seem right and can lead to not really usable built-in terminal.</s>
    Tracked in #26857.
- [x] Consider tweaking built-in tree-sitter and LSP highlight groups. Both [defaults](https://github.com/neovim/neovim/blob/0d885247b03439ee3aff4c0b9ec095a29bb21759/src/nvim/highlight_group.c#L218-L289) (tried to not alter them at all) and maybe for filetypes with built-in tree-sitter parsers (Lua, C, vimdoc, markdown). Related/blocker: https://github.com/nvim-treesitter/nvim-treesitter/issues/4799.
    - <s> Look into redoing default links so that `@` highlight groups mostly link to themselves. Exceptions are the "core" ones which should link to Vim's group (not breaking) **or** be defined with colors while Vim's group link to them instead (major breaking for Vim's color schemes). </s>
        Addressed in #27188 and #22981.

- [X] <s> Consider tweaking filetype plugin highlight groups. One notable example is 'diff' as it [links `diffRemoved` to `Special`](https://github.com/neovim/neovim/blob/0d885247b03439ee3aff4c0b9ec095a29bb21759/runtime/syntax/diff.vim#L381) (`diff*`) making patches look unhighlighted (removed) and blue (added). </s>
    Addressed in f46ae1368530389129b5f7f1768c057d5d0b9c2f.
- [x] ~ Fix bundled colorschemes by adding `colorscheme vim` after `hi clear`. ~ Addressed in #26641
- [x] <s> Update tests to use new color scheme instead of relying on `colorscheme vim`. I am committed to doing it after all highlight groups are settled and some screen test behavior is confirmed to be ok (like using new indexes for attributes instead of replacing previous ones).</s> Tracked in #28601

**Comment by justinmk** [comment]
> As there are only cyan and blue available (green is for strings) I decided to leave Special unhighlighted.

I've been using "light cyan" for Special. We can use variations of green/blue/gray where we need distinction. No need to add a color to the palette.

**Comment by tomtomjhj** [comment]
Thanks a lot for working on this. Not sure if this is the right place, but here are some minor issues I encountered
* insufficient emphasis (even the `quiet` built-in colorscheme uses noisy colors for these)
    * `QuickFixLine`
    * `Todo`
* undistinguishable pairs
    * `Search` vs. `CurSearch`
    * `FoldColumn` vs. `LineNr`: if you have small `foldcolumn`, the fold column shows foldlevel numbers, so it should be distinguishable from line numbers

Fixing these may not align with minimalism, but I think it would be quite useful.

**Comment by echasnovski** [comment]
> I've been using "light cyan" for Special. We can use variations of green/blue/gray where we need distinction. No need to add a color to the palette.

Using any other color outside of `Nvim{Dark,Light}{Green,Blue,Cyan}` will mean adding a color to palette, though. I tried adding a desaturated variants of green and cyan, but that doesn't work for light color scheme (they are almost indistinguishable from regular green and cyan).

------

@tomtomjhj, thanks!

- `QuickFixLine` and `Todo` are bold as it seems to be quite sufficiently "noisy" highlighting.
- Both `Search`/`CurSearch` and `FoldColumn`/`LineNr` have same highlighting, yes. This is indeed the result of "be minimal" and lack of good colors to use considering "green-blue" requirement.

**Comment by clason** [comment]
I think having `Special` being indistinguishable from another "highlight" color is (much) preferable to `Special` being indistinguishable from the base foreground color (i.e., not highlighted at all). So just using `NvimLightCyan` for it would be a significant improvement IMO.

**Comment by famiu** [comment]
My opinion on this is purely subjective as I lack any knowledge in color theory, but I personally find that the default background on both the light/dark themes lack contrast. I think making increasing contrast for both backgrounds would be a big improvement.

**Comment by cbarrete** [comment]
> Using bold text for keywords is intentional to show structure without use of color, which matters for accessibility.

For some languages like SQL, sure, but for most languages (C-like, ML-like, etc.), the structure mostly comes from indentation and/or punctuation. It's not clear to me that the hypothetical gain in accessibility is worth the increased distraction/visual noise.

>  Comment should be less visible than text, but still distinguishable.

Is this a subjective statement, or do you have something to back it up? I subjectively strongly disagree, but that's only based on my experience :shrug:

> For me having CurSearch have bold text with regular one in Search is enough distinction. But that is, of course, subject to debate.

I like the idea! I've just tried it and it's hard to distinguish for me, but that's at least better than no bold at all.

For the rest, I agree that it's mostly personal preference, I suppose that I don't *technically* get to complain about a ratio > 7.

**Comment by echasnovski** [comment]
> > lightness of background was taken from the reference color scheme at the time.
> 
> I appreciate that, but the new theme definitely has less contrast than the reference theme. For `Normal` we should edge towards a bit more contrast. For things like PMenu/floats we can swap to the lighter bg. The common case should be a bit higher contrast, the less-common cases (PMenu/floats) can opt to lower contrast if needed.

Introducing more contrast is not really a problem. I had reference lightness values being equal to `{ 6, 13, 20, 35 }`, but I can change to, say, `{ 4, 8, 16, 32 }`. This will make dark palette darker and light palette lighter.

I am not really a fan having floating windows having lighter background (for dark variant), as I outlined in [this comment](https://github.com/neovim/neovim/pull/26334#issuecomment-1835670432). Of course, it is doable, just something I can't consider being a good UI.

**Comment by echasnovski** [comment]
Just as a side note. I plan to have this for at least a week to gather feedback (at least until after Neovimconf) and make a follow up PR addressing the least controversial changes.

**Comment by MunifTanjim** [comment]
`DiagnosticFloating*` hl groups now has `bg`, so they don't blend with the `NormalFloat`. So they look very odd:

![image](https://github.com/neovim/neovim/assets/8050659/1d764005-5e98-4223-bce9-503aa16e7577)

These hl groups should only define `fg`, so that the `bg` from `NormalFloat` is used.

**Comment by lazywei** [comment]
Noticed that with the default colorscheme in background=light mode, the cursor is almost not readable.
<img width="707" alt="image" src="https://github.com/neovim/neovim/assets/2840571/b506a59e-9cc8-4665-8a63-b03cd4563790">

Not sure if this is expected (like do I need to tune any config?) or is this by-design?

**Comment by towry** [comment]
> Noticed that with the default colorscheme in background=light mode, the cursor is almost not readable. <img alt="image" width="707" src="https://private-user-images.githubusercontent.com/2840571/288626754-b506a59e-9cc8-4665-8a63-b03cd4563790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjkxMzAsIm5iZiI6MTcwMTkyODgzMCwicGF0aCI6Ii8yODQwNTcxLzI4ODYyNjc1NC1iNTA2YTU5ZS05Y2M4LTQ2NjUtOGE2My1iMDNjZDQ1NjM3OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDYwMDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlkYzE5ZGU3MTkwYTk3MGU5ZTQ4N2M1MjY2YzdiOTAxM2E5NzBlMDg4ZmM5NGRjYWJiMTgxYzNlYTFjZTJiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4cd7FzSZ5dYabyqdZI4rYq_NYtK62O73VqytNLkJfjs">
> 
> Not sure if this is expected (like do I need to tune any config?) or is this by-design?

Perhaps you need to adjust the cursor color in your terminal settings, such as:

```
#: Cursor colors

cursor                          #2e2c2f
cursor_text_color               #e1e4dc

```

in kitty.

**Comment by craigmac** [comment]
> Noticed that with the default colorscheme in background=light mode, the cursor is almost not readable.

If the terminal emulator supports it, most do, you can do:

```lua
vim.opt.guicursor:append({'a:Cursor'})
```

And now the cursor will obey what `:hi Cursor` is set to. For example in my init.lua I use:

```lua
-- Use `:hi Cursor` as default hl-group to cursor in (a)ll modes
vim.opt.guicursor:append({'a:Cursor'})

-- Works in most terminal emulators - always works in GUI
vim.cmd[[hi! Cursor guibg=Magenta]]
```

**Comment by craigmac** [comment]
A few of the tweaks I've made when `:set background=light`:

```lua
 -- Lighten ColorColumn to fix Comment guifg being unreadable
 vim.cmd[[hi! ColorColumn guibg=NvimLightGrey1]]
 -- Lighten Visual to fix Comment guifg being unreadable
vim.cmd[[hi! Visual guibg=NvimLightGrey3]]
```

**Comment by Jendker** [comment]
Is there a way to avoid the change of the background transparency on nightly to the previous behavior? During startup I can first see black background which jumps later to transparent. Or is it something planned for this follow up?

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/26550
https://github.com/neovim/neovim/pull/26579

**Comment by jdrouhard** [comment]
Awesome theme! I did notice one thing that might need a slight tweak. Seems like `@namespace` is linked to `Identifier`, but `@lsp.type.namespace` is linked to `Structure` (which links to `Type`). This results in a loss of color (since `Type` is the "normal" color by default) when enabling semantic tokens for languages with namespaces:

<details>
<summary>screenshots</summary>

Without semantic tokens:
![image](https://github.com/neovim/neovim/assets/394891/48c63f45-d08f-4fa1-9d47-43dfd883bff6)

With semantic tokens:
![image](https://github.com/neovim/neovim/assets/394891/3e736004-46e4-4ece-832c-e2037805fe6f)
</details>

Notice the `std` namespace is colored with treesitter only, but drops back to uncolored when semantic tokens kick in. I think just updating `@lsp.type.namespace` to link to Identifier would be a good tweak.

**Comment by clason** [comment]
Please see above; the non-basic (LSP and treesitter groups) are still todo.

**Comment by clason** [comment]
https://github.com/vim/vim/commit/e6d8b4662ddf9356da53f56e363b67b524fd8825

**Comment by etorth** [comment]
Just a comment:

experts,
please make diff mode relatively higher contrast.
please use different color for different diff pattern (add/delete/modify)
please distinguish colors between searching highlight and diff highlight, because we still do searching in diff mode.

**Comment by echasnovski** [comment]
> Just a comment:
> 
> experts, please make diff mode relatively higher contrast. please use different color for different diff pattern (add/delete/modify) please distinguish colors between searching highlight and diff highlight, because we still do searching in diff mode.

All this is already addressed.

**Comment by clason** [comment]
I think we can consider the user-facing side (that should be in 0.10) complete; the remaining issues are follow-ups that can go into 0.11 (or be backported if necessary).

Thank you @echasnovski for all your tireless work on this! 

(And feel free to close this now if you don't think you'll need a dedicated tracking issue for the test changes.)

**Comment by echasnovski** [comment]
Yep. The two remaining tasks are split and tracked in #26857 and #28601.

Thanks everyone for the useful feedback!
