### ISSUE TITLE
ui2 (extui): ext_cmdline/message for the TUI: tracking issue

### ISSUE THREAD

**Issue by luukvbaal** [neovim/neovim#27811]
I will be working on an ext_cmdline/message implementation for the TUI. An internal C implementation was explored first, but dropped after coming to the conclusion that properly untangling the current cmdline from the message grid in C would require more work than leveraging and improving the already existing parallel ext_ code path.

**Goals/progress:**
- [x] Introduce an experimental ext_cmdline/messages UI: #27855.
- [ ] Remove redundant C components:
	- [ ] Unmaintained Vimscript parser and cmdline highlighter.
	- [ ] Message grid.

**Comment by luukvbaal** [comment]
Okay, I have basically finished the necessary plumbing for an initial ext_cmdline/message implementation(#27855). Now I find myself wondering if it will really be worth the effort to try to spoof the current message grid implementation if we intend to move away from it later. My initial implementation is close but actually making all screen tests pass will require more work. Maybe we @neovim/core @neovim/padawans should try to settle on what the default cmdline/message should look like first.

I think there is merit in keeping the cmdline in the current 'cmdheight' area, as anything else might be too "unfamiliar"? If we don't care about that and can settle on a better alternative, I'm all for it. E.g. a floating window without borders on the last row (potentially on top of the statusline), or a floating window with borders positioned elsewhere.

I suppose the most obvious candidate for an alternative message window would be a floating window with or without borders in the bottom right corner.

Welcoming discussion.

**Comment by przepompownia** [comment]
After merge #31167  I started to try what is currently possible without FFI hacks and what issues can wait for the user and store the result in https://github.com/przepompownia/mini-ui-messages-example. It has two init files with shared redirection logic: the first uses modified mini.notify, the second displays messages in a custom way. 

`n` in normal mode causes sending two `msg_show` events: the first one with empty `kind`, the second with  `search_count` (unless we have added `S` to `shortmess`). Probably it would be good to assign some special kind to the first (I don't know if it requires anything in Vim too).
 
On the other side, commands like `:=1`, `:={x=1, y=1}` results with `msg_show` events and empty `kind`. I guess it's impossible to distinguish such messages from the search output. I also didn't find any Vim option to silent search events completely.

**Comment by przepompownia** [comment]
Let me link #22914 as possibly related - otherwise please mark it as offtopic.

**Comment by justinmk** [comment]
The subissues is overflowing, shall we create a new parent issue?

**Comment by luukvbaal** [comment]
Do we need a new one now that we have a ui2 label anyways?

**Comment by clason** [comment]
A tracking issue is useful if it has a specific goal; a natural one would be to remove all blockers for enabling this in 0.12. (We don't actually need to enable it by default; this just sets a goal for when we can consider this issue "done" and close it, after the 0.12 release if necessary.)

A more strict/longer-term goal could be to be able to remove the legacy message grid.

In particular, this would imply that we don't need to track every minor fix or "nice to have"/cosmetic enhancement.
