### ISSUE TITLE
release checklist 0.11

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#28770]
(previous: https://github.com/neovim/neovim/issues/23235)

- [Release guidelines](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#release-policy)
- [Dependencies](https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies)

# Blocking issues

<img width="446" alt="image" src="https://github.com/neovim/neovim/assets/1359421/032fc235-ed2e-4ce4-8198-86a9c5b20d84">

# Pre-release (early)

- [x] ~~run `scripts/download-unicode-files.sh`~~ (utf8proc 4tw)
- [x] Bump deps in [cmake.deps/deps.txt](https://github.com/neovim/neovim/blob/master/cmake.deps/deps.txt)
    - [x] run `scripts/bump_deps.lua` (luajit, luv, libuv, treesitter)
    - [x] treesitter parsers (C, Lua, Viml, Vimdoc, Query)
        - [x] update queries from nvim-treesitter
    - [x] lpeg (also in `neovim/deps`)
    - [x] libvterm (also in `neovim/deps`)
    - [x] msgpack
    - [ ] [wintools](https://github.com/neovim/neovim/blob/9319d97679053a219b1701d70abce414d0f6a8b0/cmake.deps/deps.txt#L28-L36)
- [x] check s930x CI logs for errors pertaining to big-endian systems (https://github.com/neovim/neovim/pull/32927)

# Pre-release

- [x] Remove deprecated functions marked for removal (`vim.deprecate(…, '0.11')`) (https://github.com/neovim/neovim/pull/32938)
- [x] Clean up `news.txt` (sorting, [phrasing](https://www.youtube.com/watch?v=Qs8Gohi1e04))
- [x] Merge `nvim.appdata.xml` changes from the maintenance branch.
- [x] Run `scripts/release.sh`

# Post-release

- [x] For major releases, create a new `release-x.y` branch.
    - **Bump the version in CMakeLists.txt** and set `NVIM_VERSION_PRERELEASE`.
- [x] Move `news.txt` to `news-x.y.txt` (and remove/update tags!). Recreate `news.txt` with "skeleton" from the old one.
- [ ] Review [revisit-at-release issues](https://github.com/neovim/neovim/labels/revisit-at-release)
- [x] Newsletter https://github.com/neovim/neovim.github.io
- [x] Update [GitHub Sponsors page](https://github.com/sponsors/neovim) (what was done, what is planned)
- [x] Update [roadmap](https://neovim.io/roadmap/)
- [ ] Remove deprecated:
    - N/A

# Merge these after release

- https://github.com/neovim/neovim/pull/32927

**Comment by justinmk** [comment]
curren blockers:

- ts async parsing
    - to unblock the release, we can just disable it by default, then re-enable on HEAD again.

**Comment by gpanders** [comment]
https://github.com/neovim/neovim/pull/32336 is a blocker for 0.11 as well (but doesn't need to be merged until just before the release).
