### ISSUE TITLE
[Overview] todo.txt as a checklist [WIP]

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#3748]
Turning the todo.txt file into a checklist without flooding the tracker with new issues. 

Let's focus on what is relevant, interesting or feasible.

/cc @Pyrohh 

# Help

- [ ] Default mapping for help files: `<Tab>` to position cursor on next |:tag|.
- [ ] Implement a "sticky" help window, some help text lines that are always
    displayed in a window with fixed height. (Guckes)  Use "~/.vimhelp" file,
    user can edit it to insert his favorite commands, new account can contain a
    default contents.
- [ ] Make 'winminheight' a local option, so that the user can set a minimal
    height for the help window (and other windows).
- [ ] ":help :s^I" should expand to ":help :substitute".
- [ ] Learn mode: show short help while typing commands.

# User Friendlier

- [ ] Add mappings local to a window: ":map <window> ..."?
- [ ] When Vim detects a file is being edited elsewhere and it's a gvim session
    of the same user it should offer a "Raise" button, so that the other gvim
    window can be displayed. (Eduard)

# Tab pages

- [ ] :tabdup	 duplicate the tab with all its windows.
- [ ] Add local variables for each tab page?
- [ ] Add local options for each tab page?  E.g., 'diffopt' could differ between
    tab pages.
- [ ] Add local highlighting for each tab page?
- [ ] Add local directory for tab pages?  How would this interfere with
    window-local directories?

# Folding

    (commands still available: zI zJ zK zp zP zq zQ zV zy zY;
    secondary: zB zS zT zZ, z=)

- [ ] Vertical folds: looks like vertically split windows, but the cursor moves
    through the vertical separator, separator moves when scrolling.
- [ ] Add "z/" and "z?" for searching in not folded text only.
- [ ] When a closed fold is displayed open because of 'foldminlines', the
    behavior of commands is still like the fold is closed.  How to make the
    user aware of this?
- [ ] Add an option 'foldskip' with values like 'foldopen' that specifies which
    commands skip over a closed fold.
- [ ] "H" and "L" count buffer lines instead of window lines. (Servatius Brandt)
- [ ] Add a way to add fold-plugins.  Johannes Zellner has one for VB.
- [ ] When using manual folding, the undo command should also restore folds.
- [ ] Allow completely hiding a closed fold.  E.g., by setting 'foldtext' to an
    empty string.  Require showing a character in 'foldcolumn' to avoid the
    missing line goes unnoticed.
    How to implement this?
- [ ] When pressing the down arrow of a scrollbar, a closed fold doesn't scroll
    until after a long time.  How to make scrolling with closed folds
    smoother?
- [ ] When creating a session, also store folds for buffers in the buffer list,
    using the wininfo in wi_folds.
- [ ] When currently editing the first file in the argument list the session
    file can contain:
	args version.c main.c
	edit version.c
    Can editing version.c twice be avoided?
- [ ] 'foldmethod' "textobject": fold on sections and paragraph text objects.
- [ ] "zuf": undo change in manual fold. "zUf" redo change in manual fold.  How
    to implement this?
- [ ] "zJ" command: add the line or fold below the fold in the fold under the
    cursor.
- [ ] 'foldmethod' "syntax": "fold=3" argument: set fold level for a region or
    match.
- [ ] Apply a new foldlevel to a range of lines. (Steve Litt)
- [ ] Have some way to restrict commands to not folded text.  Also commands like
    searches.

# Syntax highlighting

- [ ] Make ":syn off" use 'runtimepath' instead of $VIMRUNTIME. (Gary Johnson)
    Should do the same for ":syn on" and ":syn manual".
- [ ] Support "containedin" argument for ":syn include", so that the defined
    cluster can be added to existing syntax items.
- [ ] C syntax: Don't highlight {} as errors inside () when used like this:
    "({ something })", often used in GCC code.
- [ ] Add a "startgroup" to a region.  Used like "nextgroup" inside the region,
    preferred item at the start of the region. (Charles Campbell)
- [ ] When editing a new file without a name and giving it a name (by writing
    it) and 'filetype' is not set, detect the filetype.  Avoid doing it for
    ":wq file".
- [ ] For "nextgroup" we have skipwhite, skipnl and skipempty.  It would be
    really nice to be able to skip with a pattern.  Or skip with a syntax
    group. (Nikolai Weibull, 2007 Feb 27)
- [ ] Make conversion to HTML faster (Write it in C or pre-compile the script).
- [ ] Be able to change only the background highlighting.  Useful for Diff* and
    Search highlighting.
- [ ] When 'number' is set highlight the number of the current line.
    Must be enabled with an option, because it slows down display updating.
- [ ] Allow the user to add items to the Syntax menu sorted, without having to
    change this for each release.
- [ ] Add a "matchcontains" for regions: items contained in the start or end
    pattern, but not in the body.
- [ ] Add a "keepend-contained" argument: Don't change the end of an item this
    one is contained in.  Like "keepend" but specified on the contained item,
    instead of the containing item.
- [ ] cpp.vim: In C++ it's allowed to use {} inside ().
- [ ] Some syntax files set 'iskeyword'.  When switching to another filetype
    this isn't reset.  Add a special keyword definition for the syntax rules?
    When this is done, use vim.vim syntax highlighting for help file examples,
    but without ":" in 'iskeyword' for syntax.
    Also need a separate 'iskeyword' for the command line, e.g., in a help
    window ":e /asdf/asdf/" CTRL-W works different.
- [ ] Add specific syntax item to match with parens/braces that don't have a
    "%" match.  :syntax nomatch cMatchError (,{,[,),},] [contained]
- [ ] Highlight the text between two matching parens (e.g., with a grey
    background) when on one of the parens or in between them.
    Option for the matchparen plugin?
- [ ] When using a cterm, and no ctermfg or ctermbg are defined, use start/stop
    sequences.	Add remark in docs that :if 'term' == "term-name" should be
    used.
- [ ] Add @spell cluster to String and Comment groups for many languages.  Will
    allow spell checking. (Fleiner)
- [ ] When listing syntax items, try to sort the keywords alphabetically.  And
    re-insert the [] if possible.
- [ ] Make it possible to use color of text for Visual highlight group (like for
    the Cursor).
- [ ] It would be useful to make the highlight group name an expression.  Then
    when there is a match, the expression would be evaluated to find out what
    highlight group to use.  Could be used to check if the shell used in a
    password file appears in /etc/shells. (Nikolai Weibull)
	syn match =s:checkShell(v:match) contained 'pattern'
- [ ] Make it possible to only highlight a sub-expression of a match.  Like
    using "\1" in a ":s" command.
- [ ] Support for deleting syntax items:
    :syn keyword cTodo remove this
    :syn match cTodo remove "pattern"
    :syn region cString remove start="this" end="that"
- [ ] Add possibility to sync on something else, when the syncing in one way
    doesn't find match.  For HTML: When no {script} is found, try looking for
    a '<'.  (Fleiner)
- [ ] Replace the synchronizing method with a state machine specification?
    Should be able to start at any line in the file, search forwards or
    backwards, and use the result of matching a pattern.
- [ ] Use parsing like awk, so that e.g., a ( without a matching ) can be
    detected.
- [ ] Make it possible to use "inverted" highlighting, invert the original
    character.  For Visual mode.  (xterm-selection already does this).
- [ ] Highlight non-printable characters with "SpecialChar", linked to
    "Special".  Display them with the digraph characters, if possible.
- [ ] Highlight the clipboard-selection with a highlight group.
- [ ] Be able to reset highlighting to its original (default) values.
- [ ] Be able to write current highlighting to a file as commands, similar to
    ":mkvimrc".
- [ ] Improve c.vim:
    - Add check for unterminated strings, with a variable to switch it on:
      "c_strict_ansi".
    - Detect unbalanced "#endif".  Requires looking back a long way...
- [ ] Add an option to restrict the updating of syntax highlighting to the
    current line while in Insert mode.
- [ ] When guessing value of 'background', the syntax file has already been
    loaded (from the .gvimrc).	After changing 'background', load it again?
- [ ] Add ":syn resync" command, to re-parse the whole file until the current
    display position.
- [ ] Should support "me" offset for a region start pattern.  To be used to
    allow searching for the end pattern inside the match of the end pattern.
    Example: syn region pikeXX start="([^{]" end=")" should work on "()".
- [ ] When using a regexp for "contains=", should delay matching with it until
    redrawing happens.  Set a flag when a group is added, check this flag when
    highlighting starts.
- [ ] Some terminals can display colors like the GUI.  Add some setting to use
    GUI colors for the terminal?  With something to define the escape
    sequence.
- [ ] It's possible for an item to be transparent, so that the colors of an item
    lower on the stack is used.  Also do this with highlighting, so that the
    user can set transparent highlighting?  E.g. a number in a C comment would
    get the color of a comment, a number in an assignment Normal. (Nikolai
    Weibull)
- [ ] Add "semitrans": Add highlighting.  E.g., make the text bold, but keep the
    colors.  And add colors, so that Green+Red becomes Yellow.
    E.g. for this html:
	<B> bold text <I> italic+bold text </B> italic text </I>
- [ ] CTRL-] checks the highlight group for finding out what the tag is.
- [ ] Add an explanation how a list of words can be used to highlight misspelled
    words.
- [ ] Add more command line completion for :syntax.
- [ ] Add more command line completion for :highlight.
- [ ] Should find a better way to parse the :syntax and :highlight commands.
    Use tables or lists that can be shared by parsing for execution and
    completion?
- [ ] Add ColorSchemePost autocommand event, so that scripts can set up their
    highlighting. (Salman Halim)
- [ ] Add a few sets of colors (e.g. Borland Turbo C one).  With a menu to
    select one of the sets.
- [ ] Add offsets to sub-matches: "\(a*\) *"he=e1-1
    'e' is end of match 'e1' is end of sub-match 1, 's2' is start of submatch
    2, etc.
- [ ] In Insert mode, when there are typeahead characters, postpone the
    highlighting (for "." command).
- [ ] Syncing on comments isn't 100% correct when / / lines mix with / * and * /.
    For example: What about a line that starts with / / and contains * /?
- [ ] Ignore / * and  * / inside strings, when syncing.
- [ ] Build a few more syntax files from the file "/usr/share/misc/vgrindefs":
    ISP, LDL, Icon, ratfor.  And check "nedit/source/highlight.c".
- [ ] Add possibility to have background color continue until the right edge of
    the window.  Useful for comment blocks and function headings. (Rogall)
- [ ] Make it possible to add "contains" items for all items in a group.	Useful
    when extending an already existing syntax file.
- [ ] Add line-continuation pattern for non-syncing items too?
- [ ] Add possibility to highlight the whole line, including the right margin
    (for comment blocks).
- [ ] Add 'hlmatch' option: List of flags:
    'c': highlight match for character under the cursor.
    'b': highlight the previous (, and its match.
    'a': highlight all text from the previous ( until its match.
	 Also for {}, <>, etc.?
    'e': highlight all braces without a match (slow?)
    OR: add an argument "cursor" to the syntax command, which means that the
    region/match/keyword is only highlighted when the cursor is on it.
    (Campbell)
    Or do it like Elvis: define text objects and how to highlight them around
    the cursor. (Iain Truskett)
- [ ] Make it possible to use all words in the tags files as Keyword.
    Can also be done with a script (but it's slow).
- [ ] Make it possible to call a ":" command when a match is found.  Should
    allow for adding keywords from the text (e.g. variables that are set).
    And allows for sections with different highlighting.
- [ ] Add highlight group for commandline: "Commandline".  Make sure it
    highlights the command line while typing a command, and any output from
    messages.  And external commands?
- [ ] SpecialKey highlighting overrules syntax highlighting.  Can't give an
    unprintable char another color.  Would be useful for ^M at end of line.
# Messages

- [ ] When using ":q" in a changed file, the error says to "add !".  Add the
    command so that beginners understand it: "use :q!".
- [ ] For 'verbose' level 12 prints commands from source'ed files.  How to skip
    lines that aren't executed?  Perhaps move the echoing to do_cmdline()?
- [ ] Use 'report' for ":bdel"?  (Krishna)  To avoid these messages when using a
    script.
- [ ] Delete message after new command has been entered and have waited for key.
    Perhaps after ten seconds?
- [ ] Make message history available in "msg" variables: msg1, msg2, .. msg9.
- [ ] When reading from stdin allow suppressing the "reading from stdin"
    message.
- [ ] When address range is wrong you only get "Invalid range".  Be a bit more
    specific: Negative, beyond last line, reverse range?  Include the text.
- [ ] Make it possible to ignore errors for a moment ('errorignore'?).  Another
    option to switch off giving error messages ('errorquiet'?).  Also an option
    not to give any messages ('quiet')?  Or ":quiet on", ":quiet off".
    Careful: For a severe error (out of memory), and when the user starts
    typing, error messages must be switched back on.
    Also a flag to ignore error messages for shell commands (for mappings).
- [ ] Option to set time for emsg() sleep.  Interrupt sleep when key is typed?
    Sleep before second message?
- [ ] In Ex silent mode or when reading commands from a file, what exactly is
    not printed and what is?  Check ":print", ":set all", ":args", ":vers",
    etc.  At least there should be no prompt. (Smulders)  And don't clear the
    screen when reading commands from stdin. (Kendall)
    --> Make a difference between informative messages, prompts, etc. and
	error messages, printing text, etc.
- [ ] Window should be redrawn when resizing at the hit-enter prompt.
    Also at the ":tselect" prompt.  Find a generic solution for redrawing when
    a prompt is present (with a callback function?).

# Scrolling

- [ ] Add "zy" command: scroll horizontally to put the cursor in the middle.
- [ ] Add option to set the overlap for CTRL-F and CTRL-B. (Garhi)
- [ ] extend 'scrollbind' option: 'scrollopt' words "search", "relative", etc..
    Also 'e'xecute some commands (search, vertical movements) in all bound
    windows.
- [ ] Add 'scrollbind' feature to make the offset of one window with the next
    one equal to the window height.  When editing one file in both windows it
    looks like each window displays a page of the buffer.
- [ ] Allow scrolling by dragging with the mouse (grab a character and move it
    up/down).  Like the "hand" in Acrobat reader.  Use Alt-LeftMouse for this?
    (Goldfarb)
- [ ] Add command to execute some commands (search, vertical movements) in all
    bound windows.
- [ ] Add 'search' option to 'scrollopt' to allow 'scrollbind' windows to
    be bound by regexp searches
- [ ] Add "z>" and "z<": scroll sideways one screenful. (Campbell)
- [ ] Add option to set the number of lines when not to scroll, instead of the
    fixed number used now (for terminals that scroll slow with a large number
    of lines but not with a single line).

# Tags

- [ ] For 'tags' wildcard in the file name is not supported, only in the path.
    This is due to it using |file-searching|. Suboptimal solution would be to
    make the filename or the whole option use |wildcards| globing, better
    would be to merge the 2 kinds of globing. originally (Erik Falor, 2008
    April 18), updated (Ian Kelling, 2008 July 4)
- [ ] Can CTRL-] (jump to tag) include a following "." and "->" to restrict the
    number of possible matches? Check tags file for an item that has members.
    (Flemming Madsen)
- [ ] Scope arguments for ":tag", e.g.: ":tag class:cPage open", like Elvis.
- [ ] When output of ":tselect" is long, getting the more-prompt, should be able
    to type the tag number directly.
- [ ] Add the possibility to use the "-t {tag}" argument multiple times.  Open a
    window for each tag.
- [ ] Make output of ":tselect" a bit nicer.  Use highlighting?
- [ ] Highlight the "tag 1 of >2" message.  New highlight group, or same as "hit
    bottom" search message.
- [ ] When using ":tag" at the top of the tag stack, should add another entry,
    so CTRL-T can bring you back to where you are now AND to where you were
    before the previous ":tag" command. (Webb)
- [ ] When doing "[^I" or "[^D" add position to tag stack.
- [ ] Add command to put current position to tag stack: ":tpush".
- [ ] Add functions to save and restore the tag stack?  Or a command to switch
    to another tag stack?  So that you can do something else and come back to
    what you were working on.
- [ ] When using CTRL-] on someClass::someMethod, separate class from method and
    use ":ta class:someClass someMethod".
    Include C++ tags changes (Bertin).	Change "class::func" tag into "func"
    with "class=class"?  Docs in oldmail/bertin/in.xxx.
- [ ] Add ":tagargs", to set values for fields:
	:tagargs class:someclass file:version.c
	:tagargs clear
    These are then the default values (changes the order of priority in tag
    matching).
- [ ] Support for "gtags" and "global"?  With ":rtag" command?
    There is an example for how to do this in Nvi.
    Or do it like Elvis: 'tagprg' and 'tagprgonce' options. (Yamaguchi)
    The Elvis method is far more flexible, do it that way.
- [ ] Support "col:99" extra field, to position the cursor in that column.  With
    a flag in 'cpoptions' to switch it off again.
- [ ] Better support for jumping to where a function or variable is used.  Use
    the id-utils, with a connection to "gid" (Emacs can do it too).  Add
    ":idselect", which uses an "ID" database (made by "mkid") like "tselect".

# Autocommands

- [ ] Put autocommand event names in a hashtable for faster lookup?
- [ ] When the SwapExists event is triggered, provide information about the
    swap file, e.g., whether the process is running, file was modified, etc.
    Must be possible to check the situation that it's probably OK to delete
    the swap file. (Marc Merlin)
- [ ] When all the patterns for an event are "*" there is no need to expand
    buffer names to a full path.  This can be slow for NFS.
- [ ] For autocommand events that trigger multiple times per buffer (e.g.,
    CursorHold), go through the list once and cache the result for a specific
    buffer.  Invalidate the cache when adding/deleting autocommands or
    changing the buffer name.
- [ ] Add TagJump event: do something after jumping to a tag.
- [ ] Add "TagJumpFile" autocommand: When jumping to another file for a tag.
    Can be used to open "main.c.gz" when "main.c" isn't found.
- [ ] Use another option than 'updatetime' for the CursorHold event.  The two
    things are unrelated for the user (but the implementation is more
    difficult).
- [ ] Add autocommand event for when a buffer cannot be abandoned.  So that the
    user can define the action taking (autowrite, dialog, fail) based on the
    kind of file. (Yakov Lerner)  Or is BufLeave sufficient?
- [ ] Autocommand for when modified files have been found, when getting input
    focus again (e.g., FileChangedFocus).
    Check when: getting focus, jumping to another buffer, ...
- [ ] Autocommand for when an option is changed.  Match buffer name or option
    name?
- [ ] Autocommands should not change registers.  And marks?  And the jumplist?
    And anything else?  Add a command to save and restore these things.
- [ ] Add autocommands, user functions and user commands to ":mkvimrc".
- [ ] Add KeymapChanged event, so that the effects of a different keymap can be
    handled (e.g., other font) (Ron Aaron)
- [ ] When trying to open a directory, trigger an OpenDirectory event.
- [ ] Add file type in front of file pattern: <d> for directory, <l> for link,
    <x> for executable, etc.  With commas to separate alternatives.  The
    autocommand is only executed when both the file type AND the file pattern
    match. (Leonard)
- [ ] Add option that specifies extensions which are to be discarded from the
    file name.  E.g. 'ausuffix', with ".gz,.orig".  Such that file.c.gz will
    trigger the "*.c" autocommands.  (Belabas)
- [ ] Add something to break the autocommands for the current event, and for
    what follows.  Useful for a "BufWritePre" that wants to avoid writing the
    file.
- [ ] When editing "tt.gz", which is in DOS format, 'fileformat' stays at
    "unix", thus writing the file changes it.  Somehow detect that the read
    command used dos fileformat.  Same for 'fileencoding'.
- [ ] Add events to autocommands:
~~~
    Error	    - When an error happens
    NormalEnter	    - Entering Normal mode
    ReplaceEnter    - Entering Replace mode
    CmdEnter	    - Entering Cmdline mode (with type of cmdline to allow
			different mapping)
    VisualEnter	    - Entering Visual mode
    *Leave	    - Leaving a mode (in pair with the above *Enter)
    VimLeaveCheck    - Before Vim decides to exit, so that it can be cancelled
		      when exiting isn't a good idea.
    CursorHoldC     - CursorHold while command-line editing
    WinMoved	    - when windows have been moved around, e.g, ":wincmd J"
    SearchPost	    - After doing a search command (e.g. to do "M")
    PreDirChanged/PostDirChanged
		    - Before/after ":cd" has been used (for changing the
		      window title)
    ShutDown	    - when the system is about to shut down
    InsertCharPost  - user typed a character in Insert mode, after inserting
		      the char.
    BufModified	    - When a buffer becomes modified, or unmodified (for
		      putting a [+] in the window title or checking out the
		      file from CVS).
    BufFirstChange  - When making a change, when 'modified' is set.  Can be
		      used to do a :preserve for remote files.
    BufChange	    - after a change was made.  Set some variables to indicate
		      the position and number of inserted/deleted lines, so
		      that marks can be updated.  HierAssist has patch to add
		      BufChangePre, BufChangePost and RevertBuf. (Shah)
    ViewChanged	    - triggered when the text scrolls and when the window size
		      changes.
    WinResized	    - After a window has been resized
    WinClose	    - Just before closing a window
~~~
- [ ] Write the file now and then ('autosave'):
~~~
				  *'autosave'* *'as'* *'noautosave'* *'noas'*
    'autosave' 'as' number  (default 0)
	    Automatically write the current buffer to file N seconds after the
	    last change has been made and when |'modified'| is still set.
	    Default: 0 = do not autosave the buffer.
~~~
   Alternative: have 'autosave' use 'updatetime' and 'updatecount' but make
   them save the file itself besides the swapfile.

# Registers

- [ ] Don't display empty registers with ":display". (Etienne)
- [ ] Add put command that overwrites existing text.  Should also work for
    blocks.  Useful to move text around in a table.  Works like using "R ^R r"
    for every line.
- [ ] When yanking into the unnamed registers several times, somehow make the
    previous contents also available (like it's done for deleting).  What
    register names to use?  g"1, g"2, etc.?
- [ ] When appending to a register, also report the total resulting number of
    lines.  Or just say "99 more lines yanked", add the "more".
- [ ] When inserting a register in Insert mode with CTRL-R, don't insert comment
    leader when line wraps?
- [ ] The `:@r` commands should take a range and execute the register for each
    line in the range.
- [ ] Add "P" command to insert contents of unnamed register, move selected text
	to position of previous deleted (to swap foo and bar in " + foo")
- [ ] Should be able to yank and delete into the "/ register.
    How to take care of the flags (offset, magic)?

# Debug mode

- [ ] Add something to enable debugging when a remote message is received.
- [ ] Add breakpoints for setting an option
- [ ] Add breakpoints for assigning to a variable.
- [ ] Add a watchpoint in the debug mode: An expression that breaks execution
    when evaluating to non-zero.  Add the "watchadd expr" command, stop when
    the value of the expression changes.  ":watchdel" deletes an item,
    ":watchlist" lists the items. (Charles Campbell)
- [ ] Store the history from debug mode in viminfo.
- [ ] Make the debug mode history available with histget() et al.

# From Elvis

- [ ] Add `:alias` command.
- [ ] Search patterns:
~~~
      \@	match word under cursor.
~~~
but do:
~~~
      \@w	match the word under the cursor?
      \@W	match the WORD under the cursor?
~~~
- [ ] ":window" command:
~~~
    :win +	next window (up)
    :win ++	idem, wrapping
    :win -	previous window (down)
    :win --	idem, wrapping
    :win nr	to window number "nr"
    :win name	to window editing buffer "name"
~~~

# From xvi

- [ ] CTRL-_ : swap 8th bit of character.

# From vile

- [ ] When horizontal scrolling, use '>' for lines continuing right of a window.

# Far future and "big" extensions

- [ ] Change layout of blocks in swap file: Text at the start, with '\n' in
    between lines (just load the file without changes, except for Mac).
    Indexes for lines are from the end of the block backwards.  It's the
    current layout mirrored.
- [ ] Make it possible to edit a register, in a window, like a buffer.
- [ ] Add stuff to syntax highlighting to change the text (upper-case keywords,
    set indent, define other highlighting, etc.).
- [ ] Mode to keep C-code formatted all the time (sort of on-line indent).
- [ ] Allow editing above start and below end of buffer (flag in 'virtualedit').
- [ ] Smart cut/paste: recognize words and adjust spaces before/after them.
- [ ] Add open mode, use it when terminal has no cursor positioning.
- [ ] Special "drawing mode": a line is drawn where the cursor is moved to.
    Backspace deletes along the line (from jvim).
- [ ] Support for underlining (underscore-BS-char), bold (char-BS-char) and other
    standout modes switched on/off with , 'overstrike' option (Reiter).
- [ ] Add vertical mode (Paul Jury, Demirel): "5vdw" deletes a word in five
    lines, "3vitextESC" will insert "text" in three lines, etc..

**Comment by fmoralesc** [comment]
Should we put in this list only those items with a priority of, let's say 8 ("as soon as possible") or less?

**Comment by justinmk** [comment]
I think the text file is good enough...

**Comment by fmoralesc** [comment]
Well, @Pyrohh just proposed removing it in #3741 , so the idea was to keep something like it around.

**Comment by Pyrohh** [comment]
Regarding `:alias`, see http://heather.cs.ucdavis.edu/~matloff/Elvis/Doc/elvistip.html#ALIAS

It seems like a shorthand for a specific use-case of `:command`, no? If so I'm not sure it's worth it.

**Comment by fmoralesc** [comment]
@Pyrohh Yeah, that seems right. Feel free to remove or add stuff to this. I didn't get the time to cover everything at first... 

Btw, I'm locking this to collaborators for now, otherwise I feel this might turn into an endless source of "grief".

**Comment by Pyrohh** [comment]
> Feel free to remove or add stuff to this. I didn't get the time to cover everything at first...

will do, thanks for starting on it at least

**Comment by fmoralesc** [comment]
I will be adding more stuff tonight, I just thought of starting it this morning before going to classes and then I've been busy the rest of the day :p 

Anyway, do you guys think my suggestion of adding only stuff marked with a priority of 8 or less is a good idea?

**Comment by Pyrohh** [comment]
> Anyway, do you guys think my suggestion of adding only stuff marked with a priority of 8 or less is a good idea?

I think it's fine, although it should still probably be dealt with on a case-by-case basis given just how many suggestions there are in `todo.txt` :P

**Comment by fmoralesc** [comment]
:+1:

I'm going to format all the stuff in bulk and then filter things out, so the state of this might be "inconsistent" for a while.

**Comment by justinmk** [comment]
Do we need this? It shows up in issue searches a lot.

**Comment by fmoralesc** [comment]
Hm... I imagine that is because of the generic title, not because it is too important. I don't think anyone would have the patience to keep up with this thing, I sure didn't. I think we should close this.

**Comment by justinmk** [comment]
It shows up in searches because of the many topics mentioned in the content :/

**Comment by fmoralesc** [comment]
I'll clear up the body, otherwise it will keep showing up.
