### ISSUE TITLE
Fix edge cases for NULL typval_T Lists

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#4615]
See vim/vim#768, later there will probably be more issues. Current list of known issues:
- [x] `map(v:_null_list, 'v:val')` returns 0. It should return v:_null_list. (#7447)
- [x] `filter(v:_null_list, 'v:val')` returns 0. It should return v:_null_list. (#7447)
- [x] `add(v:_null_list, 1)` returns 1, it should fail. Though with locked list it returns 1 as well, so probably it should fail and return 1. (#7695, #7708)
- [x] `extend(v:_null_list, [])` returns 0, it should fail. Again locked list returns 0 and fails. (#5119)
- [x] `setreg('x', v:_null_list)` crashes. Already reported. (#5835)
- [x] `setline(1, v:_null_list)` crashes. `append()` is fine. (#7708)
- [x] `v:_null_list == v:_null_list` returns 0. NULL list is not equal to itself! `is` operator works as expected. (#5119)
- [x] Same for `v:_null_list == []`: returns 0, should return 1. (Considered to be not a bug.)
- [x] `islocked('v:_null_list')` does not crash. Though it does not return 1. I am not sure whether this needs to be fixed because e.g. `islocked('v:throwpoint')` is also zero (as it is VAR_FIXED and not VAR_LOCKED).
- [x] `v:_null_list + any_other_list` is `E15: Invalid expression`, as well as `any_other_list + v:_null_list`. Since `list + list` produces a new list it should work like `[] + any_other_list`. (#5119)
- [x] `count([v:_null_list], v:_null_list)` returns 0 in place of 1. Guess same problem as with `==`. (#5119)
- [x] `extend([1], v:_null_list)` returns 0 in place of returning `[1]`. (#5119)
- [x] `inputlist(v:_null_list)` treats this as non-list. (#7708)
- [x] `writefile(v:_null_list, "/tmp/test.fname")` returns 0, but does not actually do anything, with empty list it creates empty file (and returns 0). (#7708)
- [x] `remove(v:_null_list, 0)` returns 0 in place of E684. (#7708)
- [x] `setqflist(v:_null_list)` returns -1 (and I guess, does nothing with quickfix list), same for `setloclist(1, v:_null_list)`. For empty list it returns 0. (#7708)
- [x] `setmatches(v:_null_list)` also returns -1 in place of 0 like with empty list. (#7708)
- [x] `sort(v:_null_list)` returns 0 in place of v:_null_list, yet does not error out. (#7708)
- [x] `string(v:_null_list)` returns empty string in place of `[]`. Neovim behaves correctly here.
- [x] `json_encode(v:_null_list)` encodes empty list as `null`, same for `js_encode()`. Neovim uses `[]` in first case and does not have `js_encode()`.
- [x] `system("cat", v:_null_list)` crashes, as well as `systemlist()`. (#7708)
- [x] `for x in v:_null_list` does not work as well, it thinks `:for` is given a non-list.
- [x] `cexpr v:_null_list` thinks it was given a non-list in place of empty list. (#7708)
- [x] `deepcopy(v:_null_list)` returns an empty string without any errors. (#5119)
- [x] `insert(v:_null_list, 1)` does not report an error. (#7708)
- [x] `rpcstart(, v:_null_list)` should not crash. (#7708)
- [x] `join(v:_null_list, "")` should return empty string like `join([], "")`. (#7708)
- [x] `msgpackdump(v:_null_list)` should treat list like empty. (#7708)

---

- [x] `dictwatcher*(v:_null_dict, …)` crashes. (#5119)
- [x] indexing v:_null_dict crashes. 1bea73a21e09990c7475b674bfc909eddf5ec698

This is missing most tests with `v:_null_dict` and `$XXX_NONEXISTENT_VAR_XXX`.

Marking this as `entry-level` because fixes in most cases should be simple and straightforward.

**Comment by ZyX-I** [comment]
To check the above I used

```lua
local helpers = require('test.functional.helpers')

local exc_exec = helpers.exc_exec
local command = helpers.command
local clear = helpers.clear
local meths = helpers.meths
local eq = helpers.eq

describe('NULL', function()
  before_each(function()
    clear()
    command('let L = v:_null_list')
    command('let D = v:_null_dict')
    command('let S = $XXX_NONEXISTENT_VAR_XXX')
  end)
  describe('list', function()
    local null_list_test = function(name, cmd, err)
      it(name, function()
        eq(err, exc_exec(cmd))
      end)
    end
    local null_list_expr_test = function(name, expr, err, val)
      it(name, function()
        eq((err == 0) and err or ('Vim(let):' .. err),
           exc_exec('let g:_var = ' .. expr))
        eq(val, meths.set_var('_var', NIL))
        meths.del_var('_var')
      end)
    end

    -- FIXME map() should not return 0 without error
    null_list_expr_test('does not crash map()', 'map(L, "v:val")', 0, 0)
    -- FIXME map() should not return 0 without error
    null_list_expr_test('does not crash filter()', 'filter(L, "1")', 0, 0)
    -- FIXME map() should at least return L
    null_list_expr_test('makes map() return v:_null_list', 'map(L, "v:val") is# L', 0, 0)
    -- FIXME filter() should at least return L
    null_list_expr_test('makes filter() return v:_null_list', 'map(L, "1") is# L', 0, 0)
    -- FIXME add() should not return 1 at all
    null_list_expr_test('does not crash add()', 'add(L, 0)', 0, 1)
    -- FIXME extend() should not return 0 without error
    null_list_expr_test('does not crash extend()', 'extend(L, [1])', 0, 0)
    -- FIXME extend() should not return 0 at all
    null_list_expr_test('does not crash extend() (second position)', 'extend([1], L)', 0, 0)
    -- FIXME Crashes
    -- null_list_expr_test('does not crash setreg', 'setreg("x", L)', 0, 0)
    null_list_expr_test('does not crash append()', 'append(1, L)', 0, 0)
    -- FIXME Crashes
    -- null_list_expr_test('does not crash setline', 'setline(1, L)', 0, 0)
    -- FIXME Should return 1
    null_list_expr_test('is equal to itself', 'L == L', 0, 0)
    null_list_expr_test('is not not equal to itself', 'L != L', 0, 1)
    null_list_expr_test('is identical to itself', 'L is L', 0, 1)
    -- FIXME Should return 1
    null_list_expr_test('is equal to empty list', 'L == []', 0, 0)
    -- FIXME Should return 1
    null_list_expr_test('is equal to empty list (reverse order)', '[] == L', 0, 0)
    -- FIXME?
    null_list_expr_test('is not locked', 'islocked("v:_null_list")', 0, 0)
    -- FIXME Should return empty list
    null_list_expr_test('can be added to itself', '(L + L)', 'E15: Invalid expression: (L + L)', NIL)
    -- FIXME Should return [1]
    null_list_expr_test('can be added to non-empty list', '(L + [1])',
                        'E15: Invalid expression: (L + [1])', NIL)
    -- FIXME Should return [1]
    null_list_expr_test('can be added to non-empty list (reversed)', '([1] + L)',
                        'E15: Invalid expression: ([1] + L)', NIL)
    null_list_expr_test('can be sliced', 'L[:]', 0, {})
    null_list_expr_test('can be copied', 'copy(L)', 0, {})
    null_list_expr_test('can be deepcopied', 'deepcopy(L)', 0, {})
    null_list_expr_test('does not crash when indexed', 'L[1]', 'E684: list index out of range: 1', NIL)
    null_list_expr_test('does not crash call()', 'call("arglistid", L)', 0, 0)
    null_list_expr_test('does not crash col()', 'col(L)', 0, 0)
    null_list_expr_test('does not crash virtcol()', 'virtcol(L)', 0, 0)
    null_list_expr_test('does not crash line()', 'line(L)', 0, 0)
    null_list_expr_test('does not crash count()', 'count(L, 1)', 0, 0)
    -- FIXME Should return 1
    null_list_expr_test('counts correctly', 'count([L], L)', 0, 0)
    null_list_expr_test('does not crash cursor()', 'cursor(L)', 0, -1)
    null_list_expr_test('is empty', 'empty(L)', 0, 1)
    null_list_expr_test('does not crash get()', 'get(L, 1, 10)', 0, 10)
    -- FIXME should be accepted by inputlist()
    null_list_expr_test('is accepted as an empty list by inputlist()',
                        '[feedkeys("\\n"), inputlist(L)]', 'E686: Argument of inputlist() must be a List', NIL)
    null_list_expr_test('has zero length', 'len(L)', 0, 0)
    null_list_expr_test('is accepted as an empty list by max()', 'max(L)', 0, 0)
    null_list_expr_test('is accepted as an empty list by min()', 'min(L)', 0, 0)
    describe('', function()
      local tmpfname = 'Xtest-functional-viml-null'
      after_each(function()
        os.remove(tmpfname)
      end)
      -- FIXME should be accepted by writefile(), return {0, {}}
      null_list_expr_test('is accepted as an empty list by writefile()',
                          ('[writefile(L, "%s"), readfile("%s")]'):format(tmpfname, tmpfname), 'E484: Can\'t open file ' .. tmpfname, NIL)
    end)
    -- FIXME should give error message
    null_list_expr_test('does not crash remove()', 'remove(L, 0)', 0, 0)
    -- FIXME should return 0
    null_list_expr_test('is accepted by setqflist()', 'setqflist(L)', 0, -1)
    -- FIXME should return 0
    null_list_expr_test('is accepted by setloclist()', 'setloclist(1, L)', 0, -1)
    -- FIXME should return 0
    null_list_expr_test('is accepted by setmatches()', 'setmatches(L)', 0, -1)
    -- FIXME should return empty list or error out
    null_list_expr_test('is accepted by sort()', 'sort(L)', 0, 0)
    null_list_expr_test('is accepted by sort()', 'sort(L) is L', 0, 0)
    null_list_expr_test('is stringified correctly', 'string(L)', 0, '[]')
    null_list_expr_test('is JSON encoded correctly', 'json_encode(L)', 0, '[]')
    -- FIXME crashes
    -- null_list_expr_test('does not crash system()', 'system("cat", L)', 0, '')
    -- FIXME crashes
    -- null_list_expr_test('does not crash systemlist()', 'systemlist("cat", L)', 0, {})
    -- FIXME should not error out
    null_list_test('is accepted by :cexpr', 'cexpr L', 'Vim(cexpr):E777: String or List expected')
    -- FIXME should not error out
    null_list_test('is accepted by :lexpr', 'lexpr L', 'Vim(lexpr):E777: String or List expected')
  end)
end)
```

placed in test/functional/viml/null_spec.lua.

**Comment by ZyX-I** [comment]
Update: `:for` also does not work with NULL list.

**Comment by ZyX-I** [comment]
Update: indexing v:_null_dict.

**Comment by bbejot** [comment]
Hey all, neovim newbie here.  HELLO!

Is this supposed to all be one big commit, or a bunch of little commits, or something in-between.  After poking around a bit, I found where these things are defined and have a fix for "extend([1], f:_null_list)" in my local copy.

**Comment by KillTheMule** [comment]
I'd say use your intuition. Small commits have the advantage of being easily squashed, so I'd lean towards that side, but not so much that reviewing gets hard.

**Comment by nikagarwal98** [comment]
Hi, I'm a newbie and was wondering if I can work any of the parts of this issue if anything is still left to be done?

**Comment by KillTheMule** [comment]
Well, @ZyX-I has been pretty diligent in his bookkeeping, so you can see what parts of this issue are still open from the list. This issue has been referenced from the fixing commits, so you have some reference even. You could just pick one item, open a PR for it and we'll go from there :)

**Comment by FlorianGit** [comment]
I looked into some more items from the list above:
 * add: I have a fix locally
 * setreg: Could not reproduce
 * setline: solved the crash locally
* remove: added the error message locally. Manual testing seems to work correctly, but this caused many autmated functional tests (mostly in autoload/shada.vim and autoload/msgpack.vim) to fail with the error I just added. I want to spent some more time looking into this tomorrow, depending on the outcome of that I will either create a pull request for the points above, or for more.

**Comment by FlorianGit** [comment]
Just created a pull request for add() and setline() functions. 
I looked enough in the remove errors to know that I won't have time to research it properly today. If someone is interested, my work so far can be seen at https://github.com/FlorianGit/neovim/tree/viml_null_list_remove_add_error   (that is the adding of an error to the remove function, not the other way around). Else I might try to continue on it later.

**Comment by ZyX-I** [comment]
About setreg: “already reported” suggests that it could’ve been fixed in Vim and fix was backported. Though null_spec.lua still needs to be updated.

**Comment by ZyX-I** [comment]
Specifically I found that: https://github.com/neovim/neovim/commit/1bea73a21e09990c7475b674bfc909eddf5ec698, #5835.

**Comment by FlorianGit** [comment]
Good point. I'll fix the test in the pull request above, referencing the commit and issue you found.

**Comment by ZyX-I** [comment]
Happened to find another error: `insert(L, 1)` does not report an error.

**Comment by ZyX-I** [comment]
I am currently in process of refactoring the code base to abstract away list implementation (not created a PR yet, but will do soon). So I am removing label `good first issue` as most of errors will be gone in process of the refactoring. Do not create any new fixes here until that is ready.

**Comment by ZyX-I** [comment]
`rpcstart()` also does not care for its second argument not being NULL.

**Comment by ZyX-I** [comment]
And `join()` happens to return zero.

**Comment by ZyX-I** [comment]
`msgpackdump()` also happens to return zero.

**Comment by justinmk** [comment]
> indexing `v:_null_dict` crashes.

This doesn't seem to happen anymore, `v:_null_dict[0]` does not crash for me. @ZyX-I can we close this?
