### ISSUE TITLE
Windows: improvements

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5229]
With the merge of #5130 Neovim now builds in Windows using MSYS2/Mingw.  This issue replaces #1749 to track Windows support in Neovim.

The list of ongoing windows related issues is [here](https://github.com/neovim/neovim/labels/platform%3Awindows). The following is a list of the most important issues, some don't have open PRs but some patches can be found in #810.

### Download links

See [Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows).

### Missing features

- [x] :terminal support (#4748, #6383)
- [x] Clipboard provider (#5964)
- [x] system() and jobstart() escaping (#5280) - python2/python3 are broken because of this.
- [x] Console TUI #3902

### Other issues

- [x] Functional tests  (#5225)
- [x] Update the wiki build [instructions](https://github.com/neovim/neovim/wiki/Building-Neovim#windowsmsys2) for windows.
- [x] Windows installer (#5200). An installer is created for tags e.g. nightly. 
- [ ] How to handle VC redistributables in the installer.
- [x] Update install wiki instructions for windows (check previous point)
- [x] Appveyor dependency caching would be a very welcome improvement
- [ ] Build warnings, e.g. type conversion that need to be fixed
- [x] Building for MSVC "should work" but this is not automatically verified by Appveyor, also some generators might not work. #8084
- [ ] Unit tests are not working in windows, due to the inability to use the luajit ffi.
- [ ] #8244 `os_setperm()` needs to be re-thought; it is nonsense on Windows [because of `uv_fs_chmod`](https://github.com/libuv/libuv/blob/e76b8838e51f6e8f1944b6c6d50c3948ed764a0b/src/win/fs.c#L1072-L1081).

**Comment by Rantanen** [comment]
> Building for MSVC "should work" but this is not automatically verified by Appveyor, also some generators might not work.

How big of a priority this is to the project team? I understand targeting only one toolchain makes the maintenance easier, but working with msys/mingw is still a bit of a hassle for most Windows developers - not to mention the Windows tooling (debuggers, etc) are built around the VC++ toolchain.

I was poking around tonight. While I did find some gists, etc. that made it seem like msvc builds were working out of the box, I had some difficulties with the current master. I did get it compiling with VS2015 in the end though.

Deps:
- Added MSVC specific Patch to `libvterm` to replace VLAs with `alloca` calls. MSVC doesn't support the C99 variable length arrays. The patch implementation mimics that of the `luv`-patch that exists in the source tree already.
- Added explicit `-DLUAJIT_LIBRARIES` option to `BuildLuv.cmake` when compiling for MSVC. At least my cmake had troubles finding the `luajit` without help.

For the cmake I had to specify `-DPYTHON_EXECUTABLE` (as my Path contains Python3 by default) and for the build set `GYP_MSYS_VERSION=2015` for libuv.

NVim:
- Conditional `#define restrict __restrict` when compiling nvim under MSVC. This is another C99 feature that MSVC doesn't support - but at least it has its own keyword for it. These were used in `kvec.h`.

Received several warnings for unsigned/signed comparisons, etc. but the builds succeeded in the end. The defines are messed up though as MSVC doesn't seem to define WIN32 by default (or at least with the current CMake files) which messes up at least the file opening routines which prevent nvim from starting properly.

So no idea how libintls, etc. even fit into the whole equation - had no problems with them during compilation but if these are linked dynamically then I guess that would explain why.

All of this kind of started from me trying to take a look at #4703 - which kind of got out of hand. Now I'm mainly curious on whether msys/mingw is the long term plan for Windows builds even if there were AppVeyor builds for MSVC.

No idea what the difference to the end user would be. :)

**Comment by equalsraf** [comment]
> I was poking around tonight. While I did find some gists, etc. that made it seem like msvc builds were working out of the box,

At some point in the past #810 did build with MSVC. Some of the missing patches are likely still there.

> How big of a priority this is to the project team?

So far the biggest problems are third-party dependencies and getting (or pushing upstream support). If possible it would be desirable to keep those out of the tree.

- libvterm patches can be found [here](https://github.com/equalsraf/libvterm-win/commits/tb-windows) but never made it upstream
- iconv and libintl (see https://github.com/neovim/neovim/issues/2837, it might be required). In particular for libraries, its not always easy to find prebuilt libraries we can use here
- gperf at build time
- gettext is usually desired too
- A way to get third-party run time dependencies, e.g. diff, to bundle with neovim

Like you mentioned the primary advantage would be debugging. But not all dependencies will play nice with MSVC debug builds, some dependencies do not know how to build debug libraries and you cannot always mix both. CMake scripts would probably need some fixes too.

> Added explicit -DLUAJIT_LIBRARIES option to BuildLuv.cmake when compiling for MSVC. At least my cmake had troubles finding the luajit without help.

This one was unexpected. You can also disable luv/busted if you don't want the tests (-DUSE_BUNDLED_LUV, -DUSE_BUNDLED_BUSTED)

> Conditional #define restrict __restrict

There was a define for this in os_defs.h. Maybe a missing include somewhere.

> No idea what the difference to the end user would be. :)

There are subtle differences. Some users reported different runtime dependency errors with mingw builds. Its also possible some of the locale stuff will be different.

I have some MSVC related stuff in this [branch](https://github.com/equalsraf/neovim/tree/windows-msvc). But I'm still getting this error https://ci.appveyor.com/project/equalsraf/neovim/build/1360/job/7qbaxvhfwacyp298

**Comment by Rantanen** [comment]
Hm. That error is interesting. I'm getting it when trying to build your branch with my toolchain - but I don't get it when building the neovim master with the same toolchain (GnuWin32 gperf, VS2015).

Maybe a bad merge somewhere?

**Comment by Rantanen** [comment]
Managed to replicate. I've been playing with Debug builds. Switched to Release and got the same error.

**Comment by andreasrosdal** [comment]
An installer for Neovim on Windows which is user-friendly and allows installation with just a few clicks would be very nice. I think this is critical to get users to begin using Neovim on Windows.

**Comment by justinmk** [comment]
@equalsraf Did we accidentally resolve the "VC redistributables" question?

**Comment by equalsraf** [comment]
I dont think so. But maybe cmake pulled something in. Also Windows 10 updates are supposed to be magic in getting this to work.

**Comment by janlazo** [comment]
Which Visual Studio version should nvim target now? I'm using VS2015 on https://github.com/neovim/neovim/pull/7786 but I have VS2017 on my Windows environment (can't find the VS2015 installer).

**Comment by justinmk** [comment]
@janlazo Any version that runs on AppVeyor is fine. 2015 would be nice, but if 2017 has a new C99 feature (for example) that makes life easier, that's fine too. AFAIK VS 2017 runs on Windows 7 and there's a free version so anyone can compile with it.

**Comment by justinmk** [comment]
The major items here were addressed.  The remaining items are covered in other issues.
