### ISSUE TITLE
defaults, part 2

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6289]
Continues #2676

- [ ] return to last position when opening file ([defaults.vim](https://github.com/vim/vim/commit/8c08b5b569e2a9e9f63dea514591ecfa2d3bb392#diff-a9189246928a79ae381f9bf6ee699c65R86))
- [ ] `display=truncate`
- [ ] `pumblend=20` (for `termguicolors`/RGB only)
- [x] in `q:` window: `au CmdWinEnter [:>] syntax sync maxlines=1 minlines=1` (or some other low number)
    - https://github.com/neovim/neovim/pull/15401 
- [x] Auto-create 'backupdir' if 'backup' is set https://github.com/neovim/neovim/pull/12666
- [x] `hidden`. Why: for 'nohidden' _without_ persistent undo, hiding a buffer loses undo info.
    - https://github.com/neovim/neovim/pull/15410 
- [x] `inoremap <C-U> <C-G>u<C-U>`
- [x] `viewoptions-=options` https://github.com/tpope/vim-sensible/pull/164
- [x] `inccommand=nosplit` #15395
- [x] `switchbuf=uselast`
- [x] `sidescroll=1` https://ddrscott.github.io/blog/2016/sidescroll/ #7984
- [x] background=dark #2894 https://github.com/neovim/neovim/issues/2676#issuecomment-114947570
    - Already the default for "most cases", see `:h 'bg'`. 
- [x] `sessionoptions+=unix,slash` 1c3ca4f18fdc, 2c1d12d0beda, #7836
- [x] `nnoremap <silent> <C-L> :nohlsearch<CR><C-L>` #15385
- [x] `:set shortmess+=F` (statusline already has this info) #8619
- [x] enable 'cscopeverbose' #7888
- [x] `fillchars=vert:│,fold:·` #7986
- [x] `wildoptions=tagfile,pum` #10384
- [x] `shortmess-=S` #10136
- [x] `nostartofline` #11135

**Comment by jamessan** [comment]
`lastline=trunc`?

**Comment by zachwhaley** [comment]
`number`?

**Comment by bounceme** [comment]
`au CmdWinEnter [:>] syntax sync maxlines=1 minlines=1` . minlines might be worth considering also. it causes the syntax to start parsing from N lines back, regardless of maxlines, if i understand right.

**Comment by chetgurevitch** [comment]
Are there any concerns over "return to last position when opening file?" I'd like to see this as a default personally.

**Comment by archSeer** [comment]
A few more suggestions:
- `set nojoinspaces`, [the rationale was in the previous issue](https://github.com/neovim/neovim/issues/2676#issuecomment-153412244). Although [vim-sensible has some arguments against.](https://github.com/tpope/vim-sensible/issues/84)
- `set lazyredraw`? but apparently it doesn't work well in neovim and [was reverted in vim-sensible for that reason](https://github.com/tpope/vim-sensible/commit/9e91be7e0fb42949831fe3161ef583363648aa58)?

I think `map Q gq` makes sense, [to match vim8 defaults](https://github.com/vim/vim/blob/23921432369e210029a26864cfb4f1537b3c3395/runtime/defaults.vim#L67-L69). (Personally, I use `nnoremap Q gqip` & `vnoremap Q gq`.)

`<C-U>` mapping was also adopted in `defaults.vim`.

**Comment by justinmk** [comment]
With 'hidden', and _without_ persistent undo, hiding a buffer loses undo info. That seems like a really bad default behavior. One of them should change.

**Comment by bfredl** [comment]
My vote is on making `hidden` the default. Or was there a previous conclusive discussion against it?

**Comment by justinmk** [comment]
'hidden' default was rejected by https://github.com/tpope/vim-sensible , but this undo behavior is a strong argument in favor.

**Comment by glacambre** [comment]
Might I suggest `:set cino+=#1`? I think it's surprising for Neovim to be able to indent every line by default using `>>` except for lines that start with a `#` in C files.

**Comment by chrisbra** [comment]
since that is a buffer-local setting, it should be set in the corresponding filetype plugin.

**Comment by glacambre** [comment]
You're right, but I believe Neovim doesn't maintain runtime files and thus adding this setting to the C filetype plugin would also change this setting for Vim users too. I think that `cino` being set to `#0` by default means that it's useful to at least a few users and I also think that `#1` is more beginner friendly. So in my opinion since Neovim seems a bit less reluctant when changing defaults to something more beginner-friendly, it would make sense for Vim and Neovim to have different `cino` settings.

Is there something wrong with setting a buffer-local setting globally, other than it feeling "not right"? It can still be overridden on a buffer-local basis, right?

**Comment by emberfade** [comment]
What about using the following concerning the undo history:

`let &undodir = tempname()`
`set undofile`

- The temporary directory where the undodir would be in is created at runtime anyway.

- Undo history during runtime.  Instead of a persistent undo history nvim will delete the directories when it closes.  

- If you don't want to set hidden you can still have an undo history.

**Comment by justinmk** [comment]
@emberfade people that want `:set nohidden` can do what they like. `set hidden` will be the default anyway. Introducing new behavior for `set nohidden` will be too complicated, and will entail us justifying why we enabled persistent undo without asking (privacy+performance implications), while not having any motivation to defend this decision.

**Comment by chrisbra** [comment]
if you don't need persistent undo feature, do not set the undofile option. Undo still works, but will be discarded at the sessions end. Just set the 'undolevels' option.

**Comment by justinmk** [comment]
@chrisbra undo is discarded when a buffer is unloaded with 'nohidden'.  Are you saying undolevels will prevent that ?

**Comment by chrisbra** [comment]
> undo is discarded when a buffer is unloaded with 'nohidden'.

correct, but I understood that hidden will be a default for neovim anyhow.

**Comment by trusktr** [comment]
What's the standard for having effectively `defaults.vim` (from Vim) in both vim and neovim?

I mnea, for example, I have `~/.vimrc` symlinked to `~/.config/nvim/init.vim` and I use a single config for both vim and neovim, and I want defaults to apply to both, and running `source $VIMRUNTIME/defaults.vim` won't work in neovim.

I could just copy/paste it into my vimrc (init.vim) I suppose.

**Comment by jamessan** [comment]
> What's the standard for having effectively `defaults.vim` (from Vim) in both vim and neovim (apart from simply copy/pasting it into vimrc or init.vim)?

`defaults.vim` is a [useless hack](https://github.com/vim/vim/issues/2042#issuecomment-328678279).  It doesn't achieve what it attempts to provide and just causes confusing changes of behavior as people adjust to using Vim.

If you want to source defaults.vim, then do so inside an `if !has('nvim')` check, but I would suggest just ignoring it and putting the settings you care about in your vimrc.

**Comment by mcepl** [comment]
> What's the standard for having effectively `defaults.vim` (from Vim) in both vim and neovim (apart from simply copy/pasting it into vimrc or init.vim)?

I don’t know about standard, but I have this as my `~/.config/nvim/init.vim`:
```vim
set runtimepath^=~/.vim,~/.vim/after
set packpath^=~/.vim
source ~/.vim/vimrc
```
It works just fine for me (but it becomes less and less useful, as I have ignored Bram’s vim for too long and I cannot make myself to care about the compatibility any more).

**Comment by gpanders** [comment]
> return to last position when opening file 

I would actually argue against this: not because it's not useful but because there are some buffers/filetypes where you *don't* want this (e.g. git commit buffers), and managing all of the exceptions could quickly become arbitrary/subjective.

**Comment by gpanders** [comment]
> nnoremap <silent> <C-L> :nohlsearch<CR><C-L>

vim-sensible also includes `diffupdate` in this, which I think is reasonable.

**Comment by rumpelsepp** [comment]
> I would actually argue against this:

What about introducing a setting with a blacklist instead?

Something like this?
```
set returnlast
set returnlast_blacklist = "commit"
```

**Comment by justinmk** [comment]
> > return to last position when opening file
> 
> I would actually argue against this: not because it's not useful but because there are some buffers/filetypes where you _don't_ want this (e.g. git commit buffers), and managing all of the exceptions could quickly become arbitrary/subjective.

Blacklist is an easy solution. It is rarely a problem. 

Let's not discussion implementations here, this thread is already too long.

**Comment by gpanders** [comment]
I'd also like to propose adding `<:>` to matchpairs.

**Comment by clason** [comment]
#15404 (separate issue to avoid too much spam here)

**Comment by justinmk** [comment]
## Status

- Only a few items remaining here.
- Create new requests as separate issues with title prefix "defaults: ".

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._

**Comment by clason** [comment]
First remaining point has been spun out as https://github.com/neovim/neovim/issues/16339; second is now included in #14790. 

I'm closing this issue so we don't have to bump it to 0.7 for the remaining points (and because we don't want tracking issues for this anyway.)
