### ISSUE TITLE
[RFC] / Master issue: Compiling under Windows (VS2013)

### ISSUE THREAD

**Issue by voltagex** [neovim/neovim#696]
I'm (sort-of) interested in getting this working under VS2013, so I'd have a native-built neovim instead of relying on MinGW or similar (although this may be a valid goal as well)

I'd like to collate issues here that are stopping compilation of neovim on Windows on VS2013, in lieu of GitHub having proper blocker/issue dependency support

For now running `cmake -G Visual Studio 12` results in:

    CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
    Could NOT find LibUV (missing: LIBUV_LIBRARY LIBUV_INCLUDE_DIR)
    Call Stack (most recent call first):
    C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules   /FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
    cmake/FindLibUV.cmake:90 (find_package_handle_standard_args)
    CMakeLists.txt:51 (find_package)

Todo:

- [x] Attempt to build neovim using cmake and VS2013

- [x] Build & install libuv somewhere that cmake can find it

- [ ] Port if_cscope to use libuv (https://github.com/neovim/neovim/pull/810#issuecomment-45277957)

- [x] start thinking about how to split platform code (os_unix.c os_msvc.c etc)
- [ ] Add bracket to if statements (maybe?)
- [ ] Start splitting compiler options in CMake
- [ ] Refactor vim_FulllName
- [ ] Add include guards: sys/time.h unistd.h
- [ ] Reorder includes here and there, i.e. ensure platform includes and/or vim.h are included before anything else

- [ ] Document the above

- [ ] ???

- [ ] Profit

Thanks to @equalsraf  for the above

**Comment by Pyrohh** [comment]
#1749 has been open for a while, so I'll close this. My apologies if I missed something.
