### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7433]
Pre-release

- [x] runtime updates
- [x] run `scripts/gen_api_vimdoc.py`
- [x] bump neovim-qt in [third-party/CMakeLists.txt](https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt)

Post-release

- [x] review [revisit-at-release](https://github.com/neovim/neovim/labels/revisit-at-release) issues
- [x] update [releases](https://github.com/neovim/neovim/releases) downloads
- [x] update https://github.com/neovim/neovim/wiki/Following-HEAD
- [x] if applicable, bump libuv/luarocks/busted/etc. versions
- [x] craft epic newsletter

**Comment by Shougo** [comment]
>  runtime updates

It seems done.

**Comment by aeosynth** [comment]
would be great if the `rust` runtime files (indent, syntax...) got synced

**Comment by Shougo** [comment]
@aeosynth https://github.com/neovim/neovim/pull/7499

**Comment by janlazo** [comment]
nvim-qt adding `../share` in `&rtp` remains unresolved as of the current nightly release.

Workaround to remove it for the bundled nvim-qt

```viml
if has('win32')
  " neovim-qt mangles the runtimepath so revert to Vim defaults
  if !isdirectory($NVIM_QT_RUNTIMEPATH)
    set runtimepath&vim
  endif
endif
```

**Comment by justinmk** [comment]
@janlazo patch welcome

**Comment by justinmk** [comment]
@janlazo I tagged 0.2.1 anyways, don't want to block it any longer. 0.2.2 can be a small release.

**Comment by Shougo** [comment]
The issue will be closed?

**Comment by justinmk** [comment]
As soon as the checklist is finished ...

**Comment by janlazo** [comment]
@justimk Nothing breaks but it's an extra directory in `runtimepath` that shouldn't be there and is specific to nvim-qt because the binary doesn't know that the gui shim plugin is included in nvim's runtime directory. nvim-qt attempts to cd `../share/nvim-qt/runtime` but that doesn't exist in shipped zip.

Reference:
https://github.com/equalsraf/neovim-qt/blob/master/src/gui/app.cpp#L224

**Comment by balta2ar** [comment]
Please don't forget to update https://launchpad.net/%7Eneovim-ppa/+archive/ubuntu/stable.
Thank you!

**Comment by justinmk** [comment]
@janlazo Thanks for that clear explanation.
