### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7507]
Pre-release

- [ ] runtime updates
- [ ] run `scripts/gen_api_vimdoc.py`
- [ ] `third-party/CMakeLists.txt`: bump neovim-qt

Post-release

- [ ] review [revisit-at-release](https://github.com/neovim/neovim/labels/revisit-at-release) issues
- [ ] update [releases](https://github.com/neovim/neovim/releases) downloads
- [ ] update https://github.com/neovim/neovim/wiki/Following-HEAD
- [ ] `third-party/CMakeLists.txt`: bump libuv/luarocks/busted/etc.
- [ ] newsletter

**Comment by bfredl** [comment]
we should also add test for ui_events similar to functions test, but relaxed according to the API event contract (new parameters allowed).
