### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8521]
Pre-release (early)

- [x] Runtime updates
- [x] Bump deps in `third-party/CMakeLists.txt` (libuv/luarocks/busted/etc.).
- [x] Bump luarocks packages (`BuildLuarocks.cmake`, #8069)
- [x] Bump neovim-qt in `third-party/CMakeLists.txt`

Pre-release

- [x] TODO in https://github.com/neovim/neovim/pull/7759/commits/6e5cb0debd23693175bd05409d3f1af4015567df#diff-0cb6905847a2464d72453b072b796f4aR154
- [x] Run `scripts/gen_api_vimdoc.py`

Post-release

- [x] Update bot-ci to [publish to "stable" tag](https://github.com/neovim/neovim/issues/9356#issuecomment-446808448)
- [x] Review [revisit-at-release issues](https://github.com/neovim/neovim/labels/revisit-at-release)
- [ ] Update [releases](https://github.com/neovim/neovim/releases)
- [x] Document [breaking changes](https://github.com/neovim/neovim/wiki/Following-HEAD) (if any)
- [ ] Newsletter

**Comment by KillTheMule** [comment]
Sublist for the newsletter:

- Update last section `Thanks` if deemed appropriate
- Rerun the commands in the penultimate section `Stats`
- Clean up the section `0.3 for Users` somewhat, I haven't been able to tune it down.

As I side node, I documented the change to stdin behavior in the wiki.

**Comment by colemickens** [comment]
Should "Publish to Pypi" be listed as well?

NixOS packages `neovim` via pypi, so I'm unable to submit an update for neovim 0.3.0, as it is not currently released on pypi.

**Comment by justinmk** [comment]
@colemickens what do you mean? https://github.com/neovim/python-client is versioned separately ...

**Comment by colemickens** [comment]
@justinmk :/ Yeah, I got confused with that, I think. Sorry for the noise...

**Comment by bfredl** [comment]
I will do 0.3 pynvim release very soon (in a few days, when I hopefully again will have a computer with a working win10 VM)
