### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9416]
Pre-release (early)

- [x] Runtime updates
- [x] Bump deps in `third-party/CMakeLists.txt` (libuv/luarocks/busted/etc.).
- [x] Bump [luarocks packages](https://github.com/neovim/neovim/pull/8069/files)
- [x] Bump neovim-qt in `third-party/CMakeLists.txt`

Pre-release

- [x] Run `scripts/gen_api_vimdoc.py`
- [x] Update `runtime/nvim.appdata.xml` `<releases>` #9974

Post-release

- [x] Review [revisit-at-release issues](https://github.com/neovim/neovim/labels/revisit-at-release)
- [x] Update [releases](https://github.com/neovim/neovim/releases)
- [x] Document [breaking changes](https://github.com/neovim/neovim/wiki/Following-HEAD), if any
- [ ] Newsletter
