### ISSUE TITLE
UI extension work (tracking issue)

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#9421]
Tracking/discussion issue for planned UI enhancements. NB: being mentioned on the list below is not a guarantee for being done at any specific time scale, nor is the order necessarily indicative of readiness/priority (except perhaps for the smaller follow-up items for multigrid, which I hope to get done pretty soon). Feel free to add stuff.

- [x] multigrid (#8455 **merged**)
  - [ ] improve size handling: non-screen functions should use requested size, not grid allocated size.
  - [ ] mouse support (extract from float PR + add tests)
  - [ ] messages on dedicated grid (when not `ext_messages`)
- [ ] floating windows (#6619)
  - [ ] for `!ext_popupmenu`: pum as float (implemented in float PR)
  - [ ] for `ext_popupmenu`: add tests for grid anchoring 
- [ ] `ext_messages` (#7466)
- [ ] `ext_windows`: UI control of layout and wincmds (#8707)
- [ ]  use `ext_popupmenu` events for wildmenu (for forward compat with preview info)
- [ ] `ext_statusline` (I have some ideas/pre-WIP code...)
- [ ] external columns (number, signs) by transmitting `win_T` info (no work done)
- [ ] "tabgrid" (#7541 but with multigrid)

**Comment by CrossR** [comment]
I've got a question that is vaguely related to the "GUI Features" proposal of GSOC (https://github.com/neovim/neovim/wiki/GSoC-2019-Ideas#gui-features).

Oni2 is currently going in a different way than Oni1, where Oni2 is going to own the entire front-end essentially, and use neovim as what powers the editing, rather than neovim powering both the editing and all the visual features (highlights, syntax, etcetc). There is some on that in the original design stuff @bryphe did for Oni2: https://gist.github.com/bryphe/ca3260914818a1293864e9fa6422a69c#a-new-view-layer

We've hit two bumps with parts of that:

1. Non-externalised features. One aspect of us owning the front end is the wealth of information that we are currently going to miss out on. For example, we aren't aware of a simple way of us getting the currently searched term highlight, or live substitution etc. This understandably is just a slow process, so I think eventually this will become less and less of an issue.

2. Scope of the externalised features. From our understanding, a lot of the APIs as they exist today transmit information about what is currently visible to neovim (as in the current lines on screen), rather than information on the whole buffer. Ie, we get syntax highlights for the lines on screen, not the whole buffer. That then makes doing something like a minimap much harder/impossible without weird hacks. Similarly, stuff like showing to the user where every search term is, highlight all parts of the code that are being substituted and so on aren't feasible. Having the APIs return the information for the full buffer when requested would be useful, though I don't know how realistic that is/what is blocking that from happening.

The proposal sounds like it is at least aware that there are UIs that are implementing their own front-ends, and we wanted to check that if the things we are hoping for are reasonable to want! I can't speak for all of us, but we are willing to help and attempt to help get this sort of thing into nvim as well, if it is appropriate.

**Comment by breja** [comment]
> For example, we aren't aware of a simple way of us getting the currently searched term highlight

Perhaps this does not fit your definition of "a simple way" but if you subscribe to the `grid_line` events and if you also have the detailed highlight info from `ext_hlstate` you can correlate highlight groups to (row,col) positions in the current viewport. Of course, this only works for the current viewport, so rendering search highlight groups in the minimap might be hard.

**Comment by bfredl** [comment]
@CrossR There is definitely awareness in nvim that the current GUI api doesn't cover the use case of embedders that do their own text rendering. I had the design document of Oni2 partially in mind when I wrote the "buffer contents" paragraph, but these issues are not completely new, also VscodeNvim and similar integrations would like to get nvim highlights by buffer positions, rather than screen positions.

Any contributions on this front would certainly be welcome, for instance design suggestions for how a protocol extension for Oni2 and similar embedders could look like.

**Comment by justinmk** [comment]
> 2\. a lot of the APIs as they exist today transmit information about what is currently visible to neovim (as in the current lines on screen), rather than information on the whole buffer. Ie, we get syntax highlights for the lines on screen, not the whole buffer.

In my mind, this is the "Syntax API" mentioned in the "Long Term" section of https://neovim.io/roadmap/ : programmatically create/query Vim syntax groups (defined structurally, not with regex: text properties / extended marks).  

In the near term we get a lot of leverage by letting "syntax" be defined by third-parties, sent to Nvim as "dumb" highlights. But in the long-term, "syntax API"  is better for integration with Vim plugins/conventions, as well as GUIs like Oni2.

One tradeoff is that whole-buffer operations can be  expensive compared to viewport context.

**Comment by bryphe** [comment]
Hey sorry for a massive braindump - but figured this would be as good of place as any to document our approach / findings between Onivim 1 & 2 so far! Thanks @CrossR for jumping in. And @bfredl - really appreciate you thinking about our case of doing our own rendering. 

## Rendering Features for Onivim 1/2

There's a multitude of features that we want to support:

- __Onivim 1__ Rendering of custom UI against tokens (buffer space -> view space transform)

Given a _range_ in a buffer (`line, column`, ), we should be able to draw a UI element at that position.  In essence, this just a function that is like `bufferSpaceToPixelSpace = (line, colum) => (pixelX, pixelY)`. 

- __Onivim 2__ Smooth scroll

Ability to scroll at the pixel-level as opposed to line-level

- __Onivim 2__ Minimap

Show a larger view of the buffer, with syntax highlighting, cursor position, etc.

- __Onivim 2__ Codelens

If you're not familiar with codelens - this is the idea:
![image](https://user-images.githubusercontent.com/13532591/55190239-b068a580-515c-11e9-8fe3-9f1d13259178.png)

Essentially it lets you drop informational bits interspersed in the code. Note that it takes up some space and could potentially change the number of visible lines in the window, depending on how many are shown.

## Challenge 1: Buffer Space to View Space Transform

One challenge we had with Oni1 is coming up with a reliable way to go from _buffer space_ (a `line`, `column`) in a buffer to pixel coordinates on the screen. For a lot of our 'enhanced UI', it really wasn't necessary for us to have this - like, for completion and hover, we just showed that at the cursor position, so it wasn't necessary. 

But we wanted to have the ability to do some more interesting things - like render images or previews next to URLs, clickable hyperlinks in code, etc. One example of how we use this 'buffer space to view space' transform is this experience when you drop in a snippet:
![image](https://user-images.githubusercontent.com/13532591/55189522-55827e80-515b-11e9-8181-7dcf6b63c075.png)

We take the _range_ of the snippet, and pass it to a function that converts from buffer space to pixel space, and then render the drop shadows above and below. 

This sounds like it should be easy! But it actually was really hard to get this logic working (it depends on a lot of factors: the window layout, whether line numbers are shown, the window size, etc). We ended up with this really crazy (and _slow_) code here:
https://github.com/onivim/oni/blob/50d89d1a5f5f77a780ff92cd667560e86d757e4e/browser/src/neovim/NeovimWindowManager.ts#L170

Essentially we query to get the top and bottom lines of the window - then we get the buffer ranges - and then we create a mapping of 'view ranges' to buffer ranges: https://github.com/onivim/oni/blob/50d89d1a5f5f77a780ff92cd667560e86d757e4e/browser/src/neovim/NeovimWindowManager.ts#L242

We made ~4 round-trip calls to Neovim for this. On Windows, when I measured the RTT for API calls, it had a high variance - anywhere from <1ms to ~4ms. With that, and the fact we were making additional API calls, we easily missed frame deadlines. One consequence of this is that scrolling was really janky for any feature that used this 'buffer space' to 'view space' mapping - it would be off for a few frames.

__Potential Mitigation:__

If there was an API to get the __screen cell position__, based on a window and a buffer position - I think that could help. But it might still be too slow to handle the scroll case. Handling the view rendering in the UI helps alleviate this for us (in fact, scrolling independent of the cursor in Onivim 2 is faster than when the cursor moves - due to the fact we don't need any RPC calls for that).

### Minimap / Smooth Scroll / Codelens Challenges

I grouped these together since they kind of together forced us down the path of a custom view layer.

Regarding the Minimap / Smooth Scroll / Codelens features in Onivim 2 - we actually discussed this at length @justinmk - creating a large Window was something we experimented a bit with. However, we still had the challenge that we didn't have a robust, fast way to create that buffer space -> pixel space mapping. In addition, the codelens feature makes this challenging - we'd be constantly resizing the view as we get different codelenses taking up space.

With Oni1, I found for most operations we tended to work in 'buffer space' - except for the rendering. And, as the rendering is performance critical path, if we incorporated it inline - we avoid the pitfalls we had in Oni1 with the round-trips needed to build up that buffer space -> screen space map, and it gives us a lot of flexibility in how we render the buffer.

The downside with our approach, though, is we have to manage all these things:
- Search highlighting
- Syntax highlighting (we offload to `vscode-textmate` for this)
- Line wrapping / virtual lines
- Folding - we need to account for this (deferring to VSCode's model)

I have some ideas for search highlighting / syntax highlighting covered below - but not sure if there is much Neovim could do for these other pieces.

### Externalization Ideas for Onivim 2

#### Externalization of Search Highlights

One of the biggest challenges we have at the moment is figuring out where search highlights should be shown via `/` and `?`. We'd like to show them in the text view, in the minimap, _and_ the scrollbar (so a complete picture of search results in the buffer).

__Potential API:__
- An `ext_searchhl` attach option - Use external search highlights

Then, during a search operation, if `ext_searchhl` was set on attach - Neovim would emit messages of the form `ui-event-search_highlight`:
`["search_highlight", highlights]` where `highlights` is a List of `[startLine, startCharacter, endLine, endCharacter]`.

We also were looking at plugins like [`incsearch.vim`](https://github.com/haya14busa/incsearch.vim) to see if we could tweak it to return a list of search positions, but I don't think thats doable (but maybe an alternative would be - to have an API to run a Vim RegEx and get match positions?)

#### Externalization of Syntax Highlighting

Another gap @CrossR mentioned was the lack of syntax highlighting. This isn't a deal-breaker per-se... since we get syntax highlights from Textmate - but it would be nice to have so that we can provide better support for Neovim plugins that use highlighting!

One thing I found interesting with `vscode-textmate` was the packed format it used to send highlights: 
https://github.com/Microsoft/vscode-textmate/blob/8870575f0a42eb75d035d93f60c6ba8fb795fc2a/src/main.ts#L212

Each line was an array of two indices - the first, a character offset, the second, a packed 32-bit integer containing information for the foreground color / background color / font style / and a 'standard token type' (we could ditch the language id!).

__Potential API:__

Taking inspiration from the current 'buffer updates' API - maybe there could be an API that lets us listen for syntax highlight changes?

`nvim_buf_attach_hl({buffer}, {send_buffer}, {opts})` - Activates syntax highlight updates from this buffer. Opts could contain some marker for an `offsetTop` and `offsetBottom` - some way to specify a _subset of the buffer_ for ranges.

When active - Neovim would send highlight updates of the form:
`["buffer_highlights", highlightUpdates]`, where `highlightUpdates` is a List of something like: `[lineNumber, highlights]`. `highlights` could be some sort of packed format like above - perhaps incorporating the highlight ID, or some other option for representing it.

An important consideration for highlights is, unlike buffer updates, we only need a subset of the view. (For Onivim 2 - it'd be guided by the extent of the minimap). I'm not sure whether this should be expressed in `opts` or some other API to adjust the visible range.

We'd also need an API to  `nvim_buf_detach_hl`.

### Other Externalization Considerations

With Onivim 2's current architecture - we actually don't require grid / draw updates. I wonder if some performance could be saved by having a mode where those aren't broadcasted? 

We also 'instrument' several Autocommands with information about the current state:
https://github.com/onivim/oni2/blob/091c69aec243811220a14a9267a9aa952669b553/assets/viml/init.vim#L32

I wonder if we could improve this by having an API to listen to autocommands? 
---

Again.. sorry for the wall of text. Let me know if you want to discuss any piece in more detail (or we can split this up in other issues).

There's still a lot of untapped potential in the API surface we haven't touched! I would like to spend more time with APIs like `nvim_get_keymap` - I think there's a lot of powerful stuff there. 

I'm also interested at some point in revisiting linking directly against `libnvim` - I think that could help mitigate the performance overhead of the RPC calls (since we could talk directly to nvim), as well as potentially sharing the buffer line memory, so we don't have it duplicated between Onivim 2 and nvim.

In addition - the ongoing externalization work is a huge help - having the messages externalized will be very beneficial for Onivim 2. 

__Thanks for all your help & hard work - Neovim is a great foundation to build on!__

**Comment by justinmk** [comment]
> If there was an API to get the **screen cell position**, based on a window and a buffer position - I think that could help. But it might still be too slow to handle the scroll case. Handling the view rendering in the UI helps alleviate this for us (in fact, scrolling independent of the cursor in Onivim 2 is faster than when the cursor moves - due to the fact we don't need any RPC calls for that).

**Comment by bryphe** [comment]
> Possible today by calling searchpos() in a server-side Lua chunk until it returns "not found". Adding a builtin function won't help performance, but would save hassle.

Ah, I didn't know about that family of functions (`searchpos`, `search`, `searchpair`)... indeed looks like we could get the full list of matches by iterating across the buffer with `searchpos`. Will explore that route - thanks for the suggestion!

**Comment by bfredl** [comment]
@bryphe Thanks for your input!

> nvim_buf_attach_hl({buffer}, {send_buffer}, {opts}) - Activates syntax highlight updates from this buffer. Opts could contain some marker for an offsetTop and offsetBottom - some way to specify a subset of the buffer for ranges.

This is roughly what I had in the back of my head, but I would make it more general: enable to subscribe to all buffer "decorations", where decoration is essentially the state that `screen.c` in nvim might make use of on top of the text itself: 
  - syntax highlighting and concealing
  - matchaddpos/nvim_buf_add_highlight
   - signs
   - virtual text.
   - etc

As @justinmk mentioned it might sense to integrate with extmark APIs, e.g. so that the UI event receives data on the same form as a "query" API function for extmarks with visual state.

> Each line was an array of two indices - the first, a character offset, the second, a packed 32-bit integer containing information for the foreground color / background color / font style / and a 'standard token type' (we could ditch the language id!).

The `ext_linegrid` extension defines a packed highlight representation as a single index into a table. Additionally `ext_hlstate` will transmit semantic information in the highlight definitions, but still use a single index for the cells. We can reuse them for the subscription API.

**Comment by bryphe** [comment]
> This is roughly what I had in the back of my head, but I would make it more general: enable to subscribe to all buffer "decorations", where decoration is essentially the state that screen.c in nvim might make use of on top of the text itself

Cool! I like the idea of generalizing the concept to encompass decorations / concealing / signs / virtual text... It means even w/o handling the grid updates - we'd potentially be able to support a broader surface area of neovim functionality. And likely could be useful for other GUI clients, too.

**Comment by mister-choo** [comment]
@bfredl Hello! I'm making an external ui for neovim and have attempted to implement a number of those protocol from the unchecked items.
Specifically 
- ext_statusline/winbar
- external columns (number, signs) by transmitting wline_T info 

I tried to infer your intentions from available information, but hit a wall, I have three questions:
1. "external columns (number, signs) by transmitting wline_T info" here it sound like external columns are semantic, but how would that deal with custom users statuscolumns? 
     - Custom statuscolumns are format strings. Locally, to implement smooth scroll, I arrived at splitting the string by segments and adding segment attribution (to cursor or to the text in the editor), though this feels like a special case for relative line numbers, as they are the only type of gutter information relating to the cursor.
2. statusline - you previously said in #9342 "add ext_statusline similar to ext_tabline, so the UI decides which statuslines to draw and where". Since laststatus=3 landed and ui2 things, ui now anchors to the statusline, which kind of conflicts with ui deciding where do draw the statusline
3. previous ext_tabline and ext_messages remove their rows from the grid.
But in #23610/#28081 we transmit are keeping the cells in the grid, but describe them with win_viewport_margins (possibly for external ui to remove). 
So for statusline, separators, statuscolumn, the intended model is "Nvim reserves the rows/cells, UI repaints them" or ar we are removing them after the capability exchange with the external ui happens?
  - Locally I currently reserve the external columns in neovim, but don't transmit the actual cells and the ui paints them over, so sort of an in-between thing
  - For statusline i tried both models locally. Removing the statusline row broke everything that anchors to it — cmdline_row, the msg_grid position, the pager's separator row.
4. I also ended up implementing one more thing - I was annoyed that the multigrid also draws the borders and takes up a cell, which might be in the center of the cell, which adds annoying issues when you are trying to compose the views nicely. So I added an ext_window_chrome capability: nvim keeps frame_T and all window commands, but stops painting separators/borders and instead emits semantic chrome per window — edge roles, border style, title/footer chunks. Here is how it looks: 
<img width="1410" height="785" alt="Image" src="https://github.com/user-attachments/assets/87e6c700-f0e9-4bff-9810-774006cbe0ee" />
<img width="1410" height="797" alt="Image" src="https://github.com/user-attachments/assets/423874d8-9982-4a38-8d12-c7aa20de8cb6" />
What is like about it is the ability to draw the borders nicely and consequently nicely compose the floating windows in front. 
   - What I'm unsure about: if separator cells stop existing, mouse drag-resize needs either a semantic resize request or the cells kept as hit-targets which circles back to 3. 
Is this functionality something upstream would want?

P.S. I understand that this is not a good first issue fit...

**Comment by bfredl** [comment]
@mister-choo as it happens, multigrid improvement is something I plan to work on now in the near future, based on own backlog and feedback from UI client implementors. I hope to respond to these items in detail quite soon, but this is very useful feedback, thanks.

**Comment by bfredl** [comment]
at least for statusline, I think the answer for the current iteration of multigrid (nvim still "owns" the layout of the screen) is that we need to move them to separate one-cell grids (or grid in singular for statusline=3). Together with some "semantic" info necessary for vertical separators, then we will be able to completely remove any `grid_line` events on the global grid 1 (Assuming ui2 but that is the future), which will simplify redraw logic (ui:s don't need to remember ghost statuslines on cells covered by windows).

For float window borders, I think we will still paint them unconditionally, but we will send multigrid ui:s the necessary info needed to safely crop the float grids and redraw some kind of border themselves. Although something like `ext_float_chrome` could be nice to skip the drawing if all clients opt in.

@mister-choo If you have code feel free to show it. it can probably be adapted in part, even if the change the design.

**Comment by mister-choo** [comment]
> [@mister-choo](https://github.com/mister-choo) If you have code feel free to show it. it can probably be adapted in part, even if the change the design.

will definitely publish the drafts later, currently continuing trying it out and bug-hunting.
Went on a wild goose chase recently, thought it was a bug with external chrome/external statuscolumn, but turns out those were ui2 issues instead, will have to double check and publish those first
